### ISSUE TITLE
Mocking public properties

### ISSUE THREAD

**Issue by ftassi** [padraic/mockery#108]
I'm not getting how to use set() andSet() methods for mocking public properties, do you have an example for that ? It would be nice to have it added to the doc as well.

Thanks

**Comment by simPod** [comment]
What if the property `page` is private?

**Comment by robertbasic** [comment]
@simPod you wouldn't access it from outside?

**Comment by simPod** [comment]
@robertbasic When creating a mock, is there a way to mock it's value without creating explicit setter?

**Comment by davedevelopment** [comment]
@simPod 

I include these functions in my test bootstrap file for quickly setting/getting private properties in tests.

``` php
function set_property($object, $property, $value)
{
    $rfc = new \ReflectionClass($object);
    $prop = $rfc->getProperty($property);
    $prop->setAccessible(true);
    $prop->setValue($object, $value);
}

function get_property($object, $property)
{
    $rfc = new \ReflectionClass($object);
    $prop = $rfc->getProperty($property);
    $prop->setAccessible(true);
    return $prop->getValue($object);
}
```

**Comment by simPod** [comment]
@davedevelopment not bad, thanks!
