### ISSUE TITLE
Interfaces inheritance support

### ISSUE THREAD

**Issue by everzet** [padraic/mockery#121]
Right now when you're trying to mock interface, which extends another one, Mockery mocks methods only for first interface, effectively making mock unusable. Mockery should mock methods of entire inheritance tree.

**Comment by bartmcleod** [comment]
Why is this issue closed? The conversation in the comments drifted from the original subject, but that is still an issue. It's also easy to reproduce by Mocking Zend\Stdlib\Hydrator\HydratorInterface from the ZF2 framework, which inherits two interfaces. Only the first of the two is being mocked. Trying to call extract($object) on the mock object yields this error "Method Mockery_9_Zend_Stdlib_Hydrator_HydratorInterface::extract() does not exist on this mock object". Should I solve this by mocking a list of interfaces (the two it is inheriting from)?

**Comment by davedevelopment** [comment]
@bartmcleod You're probably looking for `m::mock()->shouldIgnoreMissing()` or `m::spy()`. Mockery mocks require you to specify calls ahead of time by default. Calling `shouldIgnoreMissing` (or using the `spy` static method instead of `mock`) gives you a double that will return null for any calls it doesn't know what to do with.

``` php
<?php

require "vendor/autoload.php";

$m = Mockery::mock("Zend\Stdlib\Hydrator\HydratorInterface");

var_dump($m instanceof Zend\Stdlib\Hydrator\HydrationInterface); // bool(true)
var_dump($m instanceof Zend\Stdlib\Extractor\ExtractionInterface); // bool(true)
```

**Comment by bartmcleod** [comment]
So that means it does mock both interfaces and this issue should remain closed and it is ok for me to add the expectation for extract() myself, because I need it to return a value defined by me, that Mockery couldn't possibly know about?

**Comment by davedevelopment** [comment]
@bartmcleod I'd say so. If you wanted to open a new issue, saying that the message "Method Mockery_9_Zend_Stdlib_Hydrator_HydratorInterface::extract() does not exist on this mock object" doesn't necessarily make sense, I'd get behind that. The method does exist, but the user hasn't specified any expectations for it.

**Comment by bartmcleod** [comment]
Added issue #475

**Comment by davedevelopment** [comment]
@bartmcleod thanks!
