### ISSUE TITLE
Mock shouldReceive expectations don't fail when not called.

### ISSUE THREAD

**Issue by wakeless** [padraic/mockery#132]
Currently this test case does not fail:

```
class MyClass { function whatever(); }
$mock = \Mockery::mock("MyClass");
$mock->shouldReceive("whatever");
```

but the alternative does fail. This doesn't seem like the intended behaviour, to me it should default to atLeastOnce();

```
$mock->shouldReceive("whatever")->once();
```

I'm happy to provide a PR if I'm right about this.

**Comment by neilpadfield** [comment]
> Is there any way I can emphasise this in the documentation better?

I suggest that you don't assume that people will read the "Declaring Call Count Expectations" section to stumble across:

> We can declare that the expected method may be called zero or more times:
> ...
> This is the default for all methods unless otherwise set.

You should (must?) mention the default behaviour in the "Declaring Method Call Expectations" section.

The terminology of "should" with no other modifier, really does imply one or more times.

The text "To tell our test double to expect a call for a method with a given name" really means, in this case, "To tell our test double that it may receive a call for a method with a given name".

Thanks for the good work, I just wanted to give feedback on your question.

**Comment by davedevelopment** [comment]
:+1: @neilpadfield 

This confusion is one of the reasons I tend to use the `allows` and `expects` calls
