### ISSUE TITLE
PHP return type mismatch error when mocking method with static return type

### ISSUE THREAD

**Issue by alexandre-da-costa** [padraic/mockery#1358]
### Mockery Version

1.6.7

### PHP Version

PHP 8.2

### Issue Description

When I try to mock a method that uses `static` return type together with `->andReturn(...)` I get PHP error of mismatched types because PHP was expecting a return of same type of the `Mockery_...` class.

### Steps to Reproduce

I have an abstract class for HubSpot Objects in `\App\Services\HubSpot\Objects\HubSpotObject`

This class has a public function (not static) "findOrFail" with return type "static" so that it would use the type or the actual object retrieved depending on the class that extends it. 

For example I have a class called HubSpotList that extends HubSpotObject. When I use to find lists I get a HubSpotList correctly.

When I try to mock HubSpotList and use this, for example:

```
$I->mock(HubSpotList::class)
            ->shouldReceive('findOrFail')
            ->andReturn(new HubSpotList([
                'objectTypeId' => '0-2',
            ]));
```

### Expected Behavior

I would receive the test HubSpotList object normally.

### Actual Behavior

I get a PHP return type mismatch error

### Exception or Error

```
Mockery_6_App_Services_HubSpot_Objects_HubSpotList::findOrFail(): Return value must be of type Mockery_6_App_Services_HubSpot_Objects_HubSpotList, App\Services\HubSpot\Objects\HubSpotList returned
```

### Additional Information

I am not sure if this is actually a bug or if there is another way to do this I am oblivious to.

**Comment by ghostwriter** [comment]
Hey @alexandre-da-costa,

My apologies for the late response.

Usually, when a methods return type is `static` or `self` we use `->andReturnSelf()`.

http://docs.mockery.io/en/stable/reference/expectations.html#declaring-return-value-expectations

eg. 
``` php
$I->mock(HubSpotList::class)
      ->shouldReceive('findOrFail')
      ->andReturnSelf();
```

**Comment by alexandre-da-costa** [comment]
> Hey @alexandre-da-costa,
> 
> My apologies for the late response.
> 
> Usually, when a methods return type is `static` or `self` we use `->andReturnSelf()`.
> 
> http://docs.mockery.io/en/stable/reference/expectations.html#declaring-return-value-expectations
> 
> eg.
> 
> ```
> $I->mock(HubSpotList::class)
>       ->shouldReceive('findOrFail')
>       ->andReturnSelf();
> ```

Hello, thank you for the answer. It helped me to see the real mistake. 

The problem is that the method should be final, not fluid. So the mistake was using static for it, instead of the final class. 

I.e. for the base `findOrFail()` I should use `HubSpotObject` which is the base class, and for child classes overriding it, I just use the child class as return type, in the example `HubSpotList`.

Doing that made the mock work like expected :)

Much appreciated.
