### ISSUE TITLE
Deprecations about drop support Metadata doc-comment in PHPUnit 12

### ISSUE THREAD

**Issue by kur4tor** [padraic/mockery#1359]
### Mockery Version

1.6.7

### PHP Version

PHP 8.3

### Issue Description

When run tests on latest PHPUnit 11.0.3 with latest mockery version the results return deprecation messages about using annotations and this support will be drop in PHPUnit 12

### Steps to Reproduce

Run tests on latest stable PHPUnit will return on each tests when is mockery used
```
1) Metadata found in doc-comment for method App\Tests\SomeTest::startMockery(). Metadata in doc-comments is deprecated and will no longer be supported in PHPUnit 12. Update your test code to use attributes instead.

2) Metadata found in doc-comment for method App\Tests\SomeTest::purgeMockeryContainer(). Metadata in doc-comments is deprecated and will no longer be supported in PHPUnit 12. Update your test code to use attributes instead.
```

### Expected Behavior

no deprecations

### Additional Information

Is all about `@before` and `@after` annotations.. for example this on line 62 in MockeryPHPUnitIntegration.php
```
    /**
     * @before
     */
    protected function startMockery()
    {
        $this->mockeryOpen = true;
    }

    /**
     * @after
     */
    protected function purgeMockeryContainer()
    {
        if ($this->mockeryOpen) {
            // post conditions wasn't called, so test probably failed
            Mockery::close();
        }
    }
```

**Comment by ghostwriter** [comment]
Hey @kur4tor,

Thank you for letting us know, we will take care of this issue.

**Comment by ruudk** [comment]
Created a PR to address the issue:
- https://github.com/mockery/mockery/pull/1386
