### ISSUE TITLE
Aliases for making stubs

### ISSUE THREAD

**Issue by davedevelopment** [padraic/mockery#140]
By default (at least without knowledge of the internals), mockery actually creates stubs rather than mocks. See #132 for further info.

As such, I think we should consider some alias methods

`stub` -> `shouldReceive`

and possibly:

`toReturn` -> `andReturn`
`toReturnUsing` -> `andReturnUsing`

Which would make the stubbing look like:

``` php 

$db->stub("connect")->toReturn(true);

$db->stub("query")->toReturnUsing(function($query) {
   // ...
});

```

It's a bit of a BC break though, as we're introducing new methods on the mocks themselves, which (albeit unlikely) could break existing use. 

If this was rolled in for 0.9 and the docs where updated accordingly, by the time we reach 1.0, we might be able to alter `shouldReceive` to default to `once()`, rather than `zeroOrMoreTimes` :wink:

**Comment by padraic** [comment]
@davedevelopment Issue closable?

**Comment by davedevelopment** [comment]
Yep, I've put lots of thought in to this and think it should come in a new version or even new lib.
