### ISSUE TITLE
Cannot use 'false' as class name as it is reserved

### ISSUE THREAD

**Issue by herndlm** [padraic/mockery#1404]
### Mockery Version

1.6.10

### PHP Version

PHP 8.3

### Issue Description

I updated from 1.6.9 and started to get `Cannot use 'false' as class name as it is reserved` for chained mocks of PDO functions.

### Steps to Reproduce

```php
        $dbConnection = Mockery::mock(PDO::class);
        $dbConnection->expects('query->fetchAll')
            ->andReturn(['foo', 'bar'])
            ->getMock();
```

### Expected Behavior

Not creating the mock class named `false` and therefore not failing with PHP 8.2+ I guess.

### Actual Behavior

Fatal error with

```
Cannot use 'false' as class name as it is reserved
```

### Exception or Error

didn't get a trace yet unfortunately, but I can help out further if the issue is unclear

### Additional Information

```sh
# cat /tmp/MockeryKNGDLg
<?php interface false {} 
```

**Comment by ghostwriter** [comment]
Hi @herndlm,

Thank you for bringing this issue to our attention.

It seems that while constructing a Demeter Chain Mock for the PDO class, Mockery attempts to construct the query method.

The method signature is as follows:

`public query(string $query, ?int $fetchMode = null): PDOStatement|false`

There might be a misinterpretation of the `false` return type as an interface.

I'll investigate this further.

—

```php
public function testPDO(): void
{
    $result = ['foo', 'bar'];

    $dbStatement = Mockery::mock(PDOStatement::class);
    $dbStatement->expects('fetchAll')
                ->andReturn($result);

    $dbConnection = Mockery::mock(PDO::class);
    $dbConnection->expects('query')
                 ->with('sql')
                 ->andReturn($dbStatement);

    self::assertSame($result, $dbConnection->query('sql')->fetchAll());
}
```

**Comment by herndlm** [comment]
nice, thx for the quick fix!
