### ISSUE TITLE
Typings for setConstantsMap does not allow array

### ISSUE THREAD

**Issue by gready-hub** [padraic/mockery#1405]
### Mockery Version

1.6.10

### PHP Version

PHP 8.0

### Issue Description

Class constants can be assigned to arrays but it's not typed so.

```php
    /**
     * Set a map of constants to be used in the mock generator
     *
     * @param array<class-string,array<string,scalar>> $map e.g. ['MyClass' => ['MY_CONST' => 123, 'OTHER_CONST' => 'foo']]
     *
     * @return void
     */
    public function setConstantsMap(array $map)
    {
        $this->_constantsMap = $map;
    }
```

### Steps to Reproduce

```php
        Mockery::getConfiguration()->setConstantsMap([
            FooBar::class => ['FOO' => ['BAR' => 123]]
        ]);
```

### Expected Behavior

Psalm with Mockery linter would pass.

### Actual Behavior

Psalm with Mockery linter does not pass. 

### Exception or Error

ERROR: InvalidArgument
at file.php:41:54
Argument 1 of Mockery\Configuration::setConstantsMap expects array<class-string, array<string, scalar>>, but array{FooBar::class: array{FOO: array{BAR: 123}}} provided

**Comment by ghostwriter** [comment]
Hey @gready-hub

Thanks for reporting this issue, it will be fixed shortly.
