### ISSUE TITLE
Mocking final classes reports unresolvable type by PHPStan

### ISSUE THREAD

**Issue by Ilyes512** [padraic/mockery#1411]
### Mockery Version

1.6.11

### PHP Version

PHP 8.2

### Issue Description

PHPStan returns `Return type of call to static method Mockery::mock() contains unresolvable type.` when I try to mock a class that is `final` (in this case it's also readonly, but the issue is caused by the final statement).

```php
$dto = \Mockery::mock(MyFinalClass::class);
```

In my PHPUnit bootstrap I setup [dg\bypass-finals](https://github.com/dg/bypass-finals) so it "technically" possible to create the mock. This has always worked up to and including version `1.6.9`. It's only the last 2 releases of Mockery that PHPStan started reporting the above errors.

### Steps to Reproduce

1. Create a final class.
2. Try and mock the final class in a PHPUnit test with `dg/bypass-finals` configured in PHPUnit's bootstrap file.
3. Run PHPStan.

### Expected Behavior

No errors PHPStan errors

### Actual Behavior

PHPStan reports on the line with `Mockery::mock()`:

```
 Return type of call to static method Mockery::mock() contains unresolvable type.
```

**Comment by ghostwriter** [comment]
Hey @Ilyes512,

You are absolutely right, that was my mistake, the doc comments were incomplete.

I believe we are working on this in #1410, can you please test that branch ` "mockery/mockery": "1.6.x-dev",` and report any other issues found by each tool you’re using for static analysis.

Thank you for reporting this issue.
