### ISSUE TITLE
Error when mocking anonymous classes

### ISSUE THREAD

**Issue by lew-tfli** [padraic/mockery#1414]
### Mockery Version

1.6.10

### PHP Version

PHP 8.2

### Issue Description

On Mockery version 1.6.10 and above, an exception is thrown when mocking an anonymous class. The issue does not exist in 1.6.9.

```
class AnonClassTest extends Mockery\Adapter\Phpunit\MockeryTestCase {
    public function testA() {
        $class = new class() extends \stdClass {};
        $mock = Mockery::mock($class::class);
    }
}
```

### Expected Behavior

The mock is created successfully

### Actual Behavior

An exception is thrown

### Exception or Error

`Mockery\Exception: Class name contains invalid characters`

**Comment by ghostwriter** [comment]
Hey @lew-tfli,

Thank you for bringing this issue to our attention.

I've created a pull request to resolve this in #1415.

Could you please test the fix branch using the following command:

`composer require mockery/mockery:dev-regression/issue-1414/mock-anonymous-classes  --dev`

Your feedback on whether the fix resolves the issue would be greatly appreciated.

**Comment by lew-tfli** [comment]
Hi @ghostwriter, this has fixed the issue.

Thank you very much

**Comment by JamesFreeman** [comment]
@ghostwriter Do you know when this will be tagged for release? I'm having the same issue.

**Comment by ghostwriter** [comment]
I’ll take care of it today,

@JamesFreeman thanks for reminding me.

**Comment by ghostwriter** [comment]
Tagged https://github.com/mockery/mockery/releases/tag/1.6.12
