### ISSUE TITLE
Mocking GearmanClient

### ISSUE THREAD

**Issue by robertbasic** [padraic/mockery#142]
Ran into a curious... behaviour while mocking GearmanClient.

    <?php
    class Foo {
        protected $c;
        public function setClient($c) {
            $this->c = $c;
        }
        public function getClient() {
            return $this->c;
        }
        public function do() {
            $c = $this->getClient();
            $c->addServer('127.0.0.1');
        }
    }

    <?php
    $cMock = m::mock("GearmanClient");
    $cMock->shouldReceive('addServer')
        ->with('127.0.0.1');

    $foo = new Foo();
    $foo->setClient($cMock);
    $foo->do();

Fails with a message

"Missing argument 2 for Mockery_515ed2c10313a::addServer(), called in /path/to/Foo.php on line <line-number-of-addServer> and defined"

Rest of the message seems cut off.

Now, addServer has two optional parameters, IP and port number. If no parameters are set on $c->addServer, or only the IP, it will fail with the same message. If I set both the IP and the port number on $c->addServer and on the with() part of the mock, it will pass.

PHP 5.4.6, mockery 0.8.0.

I will look into it over the weekend. Seems like reflection sets the optional parameters to required ones?

**Comment by davedevelopment** [comment]
@robertbasic good call

**Comment by robertbasic** [comment]
Sorry it took me almost 2 years! :D
