### ISSUE TITLE
Mockery does not take __unset from mocked object

### ISSUE THREAD

**Issue by Bartzy** [padraic/mockery#150]
Hey,

On this file: https://github.com/padraic/mockery/blob/master/library/Mockery/Generator.php#L190

Mockery takes magic methods from the object that is being mocked (__set, __get, __wakeup etc), but it doesn't take the __unset magic method.

Is there any special reason for that?

Thanks,
Bar.

**Comment by padraic** [comment]
@davedevelopment Time being time, chances are this is already being mocked in the wild. Do we even want to go there at this point in changing how __unset is handled?

**Comment by davedevelopment** [comment]
@padraic I don't particularly, it's not really a valid case for me.

**Comment by davedevelopment** [comment]
@padraic I don't particularly, it's not really a valid case for me.

**Comment by padraic** [comment]
No problem.
