### ISSUE TITLE
preg_match error

### ISSUE THREAD

**Issue by rklak** [padraic/mockery#160]
The problem is when you want to fire a function ->with() with parameters that are not suitable for preg_match $pattern. 

Example:

     $mockClass = Mockery::mock('My_Keyer');
     $mockClass->shouldReceive('getElementByName')->with('Group[0][Test]')->andReturn('Passed');

Effect:
      Warning : preg_match(): Delimiter must not be alphanumeric or backslash : ....Mockery\Expectation.php@278

because: ->with('Group[0][Test]')

The warnning shows up even if there is a '@' in \Mockery\Expectation::_matchArg

    $result = @preg_match($expected, (string)$actual);

but the test passed OK even there is a warning.

Enviroment:
PHP 5.4
PHPUnit test was fired in Netbeans 7.3

**Comment by robertbasic** [comment]
@davedevelopment @padraic this one can also be closed as per #330 and #302

**Comment by padraic** [comment]
Closing as recommended by @robertbasic

**Comment by robertbasic** [comment]
@padraic the close it! :P

**Comment by davedevelopment** [comment]
:)

**Comment by padraic** [comment]
@robertbasic Hehe
