### ISSUE TITLE
shouldn't need to specify m::any() for optional parameters

### ISSUE THREAD

**Issue by shieldo** [padraic/mockery#167]
If I have a method as follows:

```
public function doThis($that, array $options = [])
{
    //do stuff
}
```

and want to declare an expectation of a call onto it where I don't care about the optional second parameter with:

```
$foo->shouldReceive('doThis')->with('that')->once();
```

it breaks because the argument list does not match. Yet:

```
$foo->shouldReceive('doThis')->with('that', m::any())->once();
```

succeeds, which seems redundant.

Can we do something sensible here like infer in the case of an optional parameter that `null` is being passed? Or is there an issue with this? Given that optional parameters are akin to overloading in, say, Java, where method definitions with the same name but different numbers of args are actually separate, I don't see a theoretical issue with this.

**Comment by padraic** [comment]
No additional feedback from the audience, so going with Dave's thumbs down.
