### ISSUE TITLE
Demeter chain mocking fails when using the fluent interface

### ISSUE THREAD

**Issue by WishCow** [padraic/mockery#171]
Using the fluent interface fails:

```php
$mock = m::mock()
    ->shouldReceive('foo->bar')
    ->andReturn(true)
    ->getMock();
$mock->foo()->bar();

// BadMethodCallException: Method demeter_foo::foo() does not exist on this mock object
```
But using the non-chained form succeeds:
```php
$mock = m::mock();
$mock->shouldReceive('foo->bar')->andReturn(true);
$mock->foo()->bar();
```

This happens both in the current dev-master (70739803f85065cc2ec00fae662bdcaaa4df487e), and 0.8.0.

**Comment by padraic** [comment]
Low priority so closing. Will review docs separately.

**Comment by davedevelopment** [comment]
@peterstarling I believe the idea was that the docs would get reviewed in one big issue...

**Comment by kirkbushell** [comment]
> [@peterstarling](https://github.com/peterstarling) I believe the idea was that the docs would get reviewed in one big issue...

Seems a sure-fire way to lose track of things that need to be done... :)
