### ISSUE TITLE
PHP Fatal error: Cannot redeclare class Mockery

### ISSUE THREAD

**Issue by SyZn** [padraic/mockery#183]
Hi,

I am using Mockery with PHPUnit for a PHP-Project, but as soon as I create two mocks of the same - non-existent class - with Mockery - in two separate tests - I always get the above error:

<code>PHP Fatal error: Cannot redeclare class Mockery_[SomeHexNumber].</code>

I've tried both: running phpunit with an without process isolation.
Any ideas?

Yours SyZn

**Comment by KartaviK** [comment]
I have same problem and root of the problem was in phpunit's method `createMock`. Its has conflicts with `Facade::shouldReceive()`. The solution is easy - just prevent usage of phpunit mocks
