### ISSUE TITLE
1.0 Discussion

### ISSUE THREAD

**Issue by davedevelopment** [padraic/mockery#288]
Just creating this as a place holder for discussions pertaining to a 1.0, will formalise something eventually.

Things I've been thinking about:
- Spies
  - Rough implementation in #283 
  - API needs discussing and finalising
- Docs
  - #90
  - @GrahamCampbell and @WouterJ have made some progress, looking to start on migrating to sphinx shortly
- API
  - Whole public API needs examining and finalising
- Stubs vs Mocks behaviours
  - IMO stubs should always be `byDefault`, i.e. you can override them
  - I would love to break the API completely, so that `shouldReceive` defaults to `once`, rather than `zeroOrMoreTimes`, along with a `stub` method, as I think the language is in conflict, but I think that's probably too much of a BC break.
- Issues
  - We need to fix and/or close issues as necessary
- User Feedback
  - Need to speak to user base to see what we're missing
- API Verifying mocks
  - Above and beyond `allowMockingNonExistentMethods`
  - Checks against method signature (for primitives and arg count etc)
  - Checks against docblock return type
  - Could be (configurably) silent when class/interface doesn't exist
  - Could be (configurably) silent when method doesn't exist

Newly added:
- PHP version support
  - PHP 5.3.x is EOL
  - See #297 
- Coding Standards
- Review state of matchers #129 
  - I think strictness with regards to objects `with($obj)` and `with(mustBe($obj))` are backwards compared to primitives.

**Comment by padraic** [comment]
@davedevelopment Should we consider moving the list to a set of separate issues under a new label?

**Comment by davedevelopment** [comment]
@padraic I think that would be a good idea, if indeed we agree on a list of things. This really was just me brain dumping things :)

**Comment by padraic** [comment]
I did a few new ones already, being full of sugar and caffeine ;). I'd suggest creating them as RFC issues with the Towards 1.0.0 label and we'll see how they play out.
