### ISSUE TITLE
mocking object via chaining methods cases code coverage to fail

### ISSUE THREAD

**Issue by dwenaus** [padraic/mockery#300]
I'm not sure this is an issue with PHPUnit or Mockery, so I'm posting it here. 

This line in my code will cause PHPUnit code coverage to fail:
$mock->shouldReceive('chained->method')->once()->andReturn([]);

however this works fine:
$mock->shouldReceive('method')->once()->andReturn([]);

**Comment by padraic** [comment]
Requires reproducible code and details, e.g. phpunit/mockery versions.

Please feel free to reopen if it remains an issue.
