### ISSUE TITLE
Incorrect expectation matching

### ISSUE THREAD

**Issue by aik099** [padraic/mockery#302]
The `_matchArg` method of the `Expectation` class is using `preg_match` to compare strings: https://github.com/padraic/mockery/blob/a32c6ad986c061b40636b7da4fe30adc2a7451b5/library/Mockery/Expectation.php#L291

Positive side effect is that you can actually pass in the regular expression to compare to, but negative side effect is that if a string doesn't have a delimiters (as regular expression does) then it creates a notice that is suspended by the `@` operator.

However then the `xdebug.scream` option is enabled, then all `@` operators are disabled all together and errors start to appear and PHPUnit catches them and fails the test in the PHPUnit strict mode.

**Comment by robertbasic** [comment]
This one could be closed, no? https://github.com/padraic/mockery/pull/330

**Comment by davedevelopment** [comment]
@robertbasic I think so.
