### ISSUE TITLE
Verify and reset expectations in mid-test

### ISSUE THREAD

**Issue by benreic** [padraic/mockery#309]
I have several different classes that I would like to apply the same test cases to, preferably in a loop. After each test inside the loop, I'd like to verify the expectations and then reset the mocks to a clean state to set new expectations. This doesn't seem to be possible, and I just wanted confirmation of that. Here is a simplified example of what I'm trying to do. 

```
class BasicTests extends UnitTestCase {

    public function tearDown ( ) {
        \Mockery::close( );
    }


    public function test ( ) {

        $mock  =  \Mockery::mock( 'Dependency' );

        $things_to_test = array(
            new Thing1( $mock ),
            new Thing2( $mock ),
            new Thing3( $mock )
        );

        foreach( $things_to_test as $thing ) {

            // 1st test
            $mock->shouldReceive( 'something' )->once( )->andReturn( true );
            $thing->run( );
            // Verify expectations and reset $mock 
            // without wiping out the container

            // 2nd test
            $mock->shouldReceive( 'something' )->once( )->andReturn( false );
            $mock->shouldReceive( 'something_else' )->twice( )->andReturn( 4, 6 );
            $thing->run( );
            // Verify expectations and reset $mock 
            // without wiping out the container

            // 3rd test
            $mock->shouldReceive( 'something' )->once( )->andReturn( false );
            $mock->shouldReceive( 'something_else' )->twice( )->andReturn( -1, 0 );
            $mock->shouldReceive( 'one_more_thing' )->once( )->andReturn( "success" );
            $thing->run( );
            // Verify expectations and reset $mock without 
            // wiping out the container
        }

    }

}
```

Is something like this possible, or do I need to move each test into its own function and then write nine test functions to cover each Thing in each test case? Thanks for your help.

**Comment by maxgalbu** [comment]
Bump, I'd like to have this, and starting new mocks doesn't override the first ones (especially for alias:)

**Comment by aik099** [comment]
@maxgalbu , it sounds like you need to have several tests and some common initialization code in `setUp` method instead. Usually doing several non-related assertions in same test is bad practice.

**Comment by maxgalbu** [comment]
They are related, i need to test the same class with different permissions.

Do I need to make a test file for each permssions instead of each class?

Mockery::close() seems works before defining overriding behaviors for a class, but resets other mocks too...

**Comment by aik099** [comment]
What you can do is to write one parametrized test and use data providers of PHPUnit.

**Comment by KKSzymanowski** [comment]
You can clear mocks like this:
```php
// Verify first
$mock->mockery_verify();
        
// and then overwrite with empty expectation directors 
foreach(array_keys($mock->mockery_getExpectations()) as $method) {
    $mock->mockery_setExpectationsFor($method, new Mockery\ExpectationDirector($method, $mock));
}
```

**Comment by JacobBrownAustin** [comment]
> // Verify first
> $mock->mockery_verify();
>         
> // and then overwrite with empty expectation directors 
> foreach(array_keys($mock->mockery_getExpectations()) as $method) {
>     $mock->mockery_setExpectationsFor($method, new Mockery\ExpectationDirector($method, $mock));
> }

I tried this and it failed.  It doesn't seem to do any verification after the first mockery_verify

**Comment by JacobBrownAustin** [comment]
It seems the problem is that the `_mockery_verified` property is initialized at false, gets set to true in `mockery_verify`, and then never goes back to false, so it basically doesn't do anything ever again.  ¯\_(ツ)_/¯
