### ISSUE TITLE
Expectation Matching Not Working for Objects

### ISSUE THREAD

**Issue by GazEdge** [padraic/mockery#328]
**Issue:**
Mockery doesn't seem to correctly compare (==) objects when using with(object).

**Expected behaviour:**
Object passed to with() in test, and object sent to mocked method should pass compare (==) and return true;

**Error behaviour:**
Mockery\Exception\NoMatchingExpectationException thrown

**Enviroment:**
MAMP, PHP 5.4.10, PHPUnit 3.7.*, Mockery 0.9.0

I have the following code in a test;

``` php
    $r = Mockery::mock('Responder');
    $g = Mockery::mock('Gateway');
    $o = new ViewPageOfPackagesInCatalogue($r,$g);
    $rr = new ViewPageOfPackagesInCatalogueResponse();

    $r->shouldReceive('respond')->with($rr)->once();
    $o->execute();
```

I get the following error: 

```
Mockery\Exception\NoMatchingExpectationException : No matching handler found for Mockery_1_Responder::respond(Use_Cases\ViewPageOfPackagesInCatalogueResponse). Either the method was unexpected or its arguments matched no expected argument list for this method

Objects: (array (
  'Use_Cases\\ViewPageOfPackagesInCatalogueResponse' => 
  array (
    'class' => 'Use_Cases\\ViewPageOfPackagesInCatalogueResponse',
    'properties' => 
    array (
    ),
    'getters' => 
    array (
    ),
  ),
)
```

To verify that my production code works, I have tried the following phpunit mock, which works as expected

``` php
    $r = $this->getMock('Responder', array('respond'));
    $g = $this->getMock('Gateway');
    $o = new ViewPageOfPackagesInCatalogue($r,$g);
    $rr = new ViewPageOfPackagesInCatalogueResponse();

    $r->expects($this->once())->method('respond')->with($rr);
    $o->execute();
```

**Comment by settermjd** [comment]
Thanks @davedevelopment. `$r->shouldReceive('respond')->with(Mockery::on(function($arg) use ($rr) {
    $this->assertEquals($rr, $arg);
});` was just what I was looking for.

**Comment by settermjd** [comment]
Then again, no that doesn't work.

**Comment by ianchadwick** [comment]
davedevelopment's example is almost there, just needs to return true/false for the check.

```php
$t = new MyExpectedObject();
$r->shouldReceive('respond')->with(Mockery::on(function($arg) use ($t) {
    return $arg == $t;
});
```

**Comment by XedinUnknown** [comment]
But why must we use `on()`, which adds complexity? I tried following the docs, but `equalTo()` doesn't exist neither as a global function, nor in the Hamcrest namespace. Isn't there just a simple function for a matcher that can loosely compare objects? And, why not have `with()` accept what `TestCase::equalTo()` returns?

**Comment by eysikal** [comment]
> ```
> with(Mockery::on(function($arg) use ($rr) {
>     $this->assertEquals($rr, $arg);
> });
> ```

I realize this thread is 10 years old, but I just Googled into it today. I think instead of `assertEquals()` we want something that returns a boolean. So this instead:
```
with(Mockery::on(function($arg) use ($rr) {
    return $arg == $rr;
});
```

**Comment by eysikal** [comment]
> But why must we use `on()`, which adds complexity? I tried following the docs, but `equalTo()` doesn't exist neither as a global function, nor in the Hamcrest namespace. Isn't there just a simple function for a matcher that can loosely compare objects? And, why not have `with()` accept what `TestCase::equalTo()` returns?

I believe you need to import `use Hamcrest\Core\IsEqual` and then you can call the static method `IsEqual::equalTo()`. I think `Mockery::on` is clearer though.
