### ISSUE TITLE
Cant access pear.survivethedeepend.com

### ISSUE THREAD

**Issue by dwisnowski** [padraic/mockery#335]
vagrant@ubuntu-server-12042-x64-vbox4210:~$ sudo pear channel-discover pear.survivethedeepend.com
Discovering channel pear.survivethedeepend.com over http:// failed with message: channel-add: Cannot open "http://pear.survivethedeepend.com/channel.xml" (Connection to `pear.survivethedeepend.com:80' failed: Connection timed out)
Trying to discover channel pear.survivethedeepend.com over https:// instead
Discovery of channel "pear.survivethedeepend.com" failed (channel-add: Cannot open "https://pear.survivethedeepend.com/channel.xml" (Connection to `pear.survivethedeepend.com:443' failed: Connection timed out))

**Comment by padraic** [comment]
Unfortunately real life threw me something and I vanished offline. I do apologise for it being down for so long then.
