### ISSUE TITLE
Support only one method per "shouldReceive" call

### ISSUE THREAD

**Issue by aik099** [padraic/mockery#345]
It's never mentioned in docs, but `shouldReceive` method in fact allows passing in any number of arguments (method names to be mocked), e.g. `$mock->shouldReceive('methodOne', 'methodTwo')->....`.

Not sure if it's clear syntax really and more over the `@param mixed` in the `MockInterface` for that method doesn't seem to look like a valid one.

**Comment by padraic** [comment]
Labelling as bug provisionally. I suppose if its not documented, I probably didn't anticipate it...

**Comment by robertbasic** [comment]
This is documented http://docs.mockery.io/en/latest/reference/expectations.html#expectation-declarations and as far as I can remember this was supported... Although I never used it.

**Comment by padraic** [comment]
Yep, I recall now. Honestly, never use it myself but it's there all the same.
