### ISSUE TITLE
Multiple calls to the same function with different arguments doesn't appear to be working

### ISSUE THREAD

**Issue by darkphoenixff4** [padraic/mockery#356]
For some reason, I can't seem to mock the same function on a mock object with different arguments.  Whenever I try to, PHPUnit dies with "ERROR: application encountered an error and can not continue."  Here's the test I'm trying to run:

```
$container
    ->shouldReceive('getService')
    ->with('session')
    ->andReturn($session)
    ->once();
$container
    ->shouldReceive('getService')
    ->with('httpRequest')
    ->andReturn($request)
    ->once();
```

As expected from the function calls, the container is a mock of a DI container.  I'm trying to get it to return mocks of used objects so I can confirm the objects are being set up the right way (this is for a bootstrap class).  I know it's the second entry because if I remove it, the test runs (fails due to missing 'getService' call, of course, but it runs).  Am I doing something wrong here?  I'm using PHPUnit 4.1.4 and the latest development release of Mockery.

**Comment by padraic** [comment]
Closing as a support request.
