### ISSUE TITLE
"No matching handler" more verbose?

### ISSUE THREAD

**Issue by dandart** [padraic/mockery#36]
I often get this error:

Mockery\Exception: No matching handler found for Mongo_Collection::updateArray(Array, Array). Either the method was unexpected or its arguments matched no expected argument list for this method

Is there an option (and if not, could there be) to say something like:

Received: array('foo'), array('bar')
Expected: array('baz'), array('bat') or
array('bat'), array('quux')

perhaps in a PHPUnit kind of way (i.e. array diffs)?

It's all very well when you know you've got the wrong array but it will help miles distinguishing what's supposed to happen and what does happen.

**Comment by padraic** [comment]
Closing as related PR merged.
