### ISSUE TITLE
HHVM Issue

### ISSUE THREAD

**Issue by GrahamCampbell** [padraic/mockery#374]
While updating hhvm's framework test suite to mockery 0.9.2, I came across an error.

For the details, see https://github.com/facebook/hhvm/pull/3676 and https://reviews.facebook.net/D22959.

*I thought I'd just let you know.*

**Comment by padraic** [comment]
HHVM! :P

@GrahamCampbell This still an issue? PR appears to be closed on the FB side.

**Comment by GrahamCampbell** [comment]
Not sure. Ping me again in a few days and I'll look into it. :)

**Comment by padraic** [comment]
Sure thing. Will be taking a peek in a few days at the hhvm builds to see if it's us or them breaking the PR checks and whether I can fix them up.
