### ISSUE TITLE
Mocking object works, but the call to method goes past return value all the way to database

### ISSUE THREAD

**Issue by BardiaAfshin** [padraic/mockery#387]
When I mock the object
```php
function test_my_method() {
        $mock = Mockery::mock(new \Symfony\Component\Console\Command\Command('migrate'));
        $mock->shouldReceive('run')->once()->andReturn(0);

        //some code to trigger class goes here
}
```

I can verify it works, because when I comment out the portion of the code in the implementation it complains that the expected call to method isn't met, however, I get an error with

There was a problem connecting to the database: SQLSTATE[HY000] [2002] No such file or directory

Help?

**Comment by padraic** [comment]
Closing as support request that appears to be answered.
