### ISSUE TITLE
Test method existance

### ISSUE THREAD

**Issue by sergeylukin** [padraic/mockery#390]
Hi,

Is it possible to mock a method and allow testing it's existance (without actually calling it) from the outside? Here is an example of current test (using `is_callable`) which returns `false` (I need it to return `true`):

```
$mock = \Mockery::mock('Foo')
  ->shouldReceive('bar')
  ->andReturn('foobar')
  ->mock();

is_callable($mock, 'bar'); // false
```

Thanks

**Comment by absolux** [comment]
I think there is a possibility to check the existence of a method in a mock object created using `makePartial()` of an existing class or from a real object.

```php
$mock = Mockery::mock('SameClass')->makePartial();
```
or simply 
```php
$mock = Mockery::mock(new SomeClass());
```
with 
```php
class SomeClass {
    function foo() { return 'bar'; }
}
```
tests :+1: 
```php 
$this->assertInstanceOf(SomeClass::class, $mock);
$this->assertTrue(method_exists($mock, 'foo'));
```
