### ISSUE TITLE
Add 'shouldNotReceive' expectation

### ISSUE THREAD

**Issue by mlessnau** [padraic/mockery#391]
I think it would be consistent to have a 'shouldNotReceive' expectation.

Currently, the way to go is writing ```$m->shouldReceive('foo')->never()```. This could then be written as ```$m->shouldNotReceive('foo')```.

**Comment by padraic** [comment]
I have no real objections. @davedevelopment ?

**Comment by robertbasic** [comment]
:+1:

**Comment by aik099** [comment]
:+1:

**Comment by davedevelopment** [comment]
Fixed in #391
