### ISSUE TITLE
How to mock hard dependence?

### ISSUE THREAD

**Issue by elfet** [padraic/mockery#398]
```php
class A() 
{
    public function foo()
    {
         $this->b = new B();
    } 
}

// ...

$a = new A();
$a->foo();
```

Is it possible to mock `B` class without modify `A` class?

**Comment by edsonmedina** [comment]
IMO, being able to mock new instances would remove the evolutionary pressure to use dependency injection and separation of concerns. Instantiating objects inside a method is a bad practice and should be discouraged.

**Comment by robertbasic** [comment]
@davedevelopment you want this blog post converted to a cookbook entry? http://robertbasic.com/blog/mocking-hard-dependencies-with-mockery

**Comment by davedevelopment** [comment]
@robertbasic if you get ten minutes, sure! The docs always need love :)

**Comment by padraic** [comment]
@edsonmedina I agree, however it's one of those pick the lesser evil choices that, while not perfect in any way, was implemented (if a bit obtusely using a special prefix keyword), so we can't backtrack support on a whim and leave existing test suites broken.

Thanks @robertbasic. Will close this once the doc is merged.
