### ISSUE TITLE
Subsequent shouldReceive() calls should override Expectations set by previous ones.

### ISSUE THREAD

**Issue by jdunk** [padraic/mockery#401]
Currently, only the first call to shouldReceive with the same parameters sets an Expectation.  Subsequent calls with the same parameters do not override this Expectation (they apparently have no effect at all).  I believe subsequent calls should override previous ones.  I'm not sure if "doing nothing" is the intended result (and if so, what the benefit would be).

__TLDR: I believe the following unit test should pass:__

```diff
diff --git a/tests/Mockery/ExpectationTest.php b/tests/Mockery/ExpectationTest.php
index 4c72330..3ee40c3 100644
--- a/tests/Mockery/ExpectationTest.php
+++ b/tests/Mockery/ExpectationTest.php
@@ -54,6 +54,13 @@ class ExpectationTest extends MockeryTestCase
         $this->assertNull($this->mock->foo('foo', array(), new stdClass));
     }
 
+    public function testExpectationCanBeOverridden()
+    {
+        $this->mock->shouldReceive('foo')->andReturn('green');
+        $this->mock->shouldReceive('foo')->andReturn('blue');
+        $this->assertEquals($this->mock->foo(), 'blue');
+    }
+
     public function testReturnsNullIfNullIsReturnValue()
     {
         $this->mock->shouldReceive('foo')->andReturn(null);
```

__Currently, it fails:__

```diff
There was 1 failure:

1) ExpectationTest::testExpectationCanBeOverridden
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'green'
+'blue'
```

**Comment by kirkbushell** [comment]
I thought there was a way you can set expectation orders? Aka, like the first one need sto be called first, if it's not it'll fail.etc. You can use the ordered() method when setting expectations to do that. That's pretty important if you have multiple calls that return different results, but really - both method call signatures should be slightly different as well.

Ie. if you have a method that returns different results but with the same arguments, there's a smelly code chunk in there...

**Comment by fhinkel** [comment]
@jdunk The first expectation will be used for exactly as many times as you specify by setting the expectation count, then the next expectation is used and so on. If you do not explicitly set the expectation count for an expectation, this expectation is used as many times as you call it, i.e., any number of times from never to infinity.

 ```
public function testExpectationWithoutCountIsUsedInfinitelyManyTimes()
{
    $this->mock->shouldReceive('foo')->andReturn('green');
    $this->mock->shouldReceive('foo')->andReturn('blue');
    $this->assertEquals($this->mock->foo(), 'green');
    $this->assertEquals($this->mock->foo(), 'green'); 
}
```

If you specify the expectation count, subsequent expectations are called as expected
```
public function testExpectationCanBeOverridden()
{
    $this->mock->shouldReceive('foo')->once()->andReturn('green');
    $this->mock->shouldReceive('foo')->andReturn('blue');
    $this->assertEquals($this->mock->foo(), 'green');
    $this->assertEquals($this->mock->foo(), 'blue');
}
```

You can implicitly set the expectation count to one on the first expectation by providing several return values to one expectation
```
public function testExpectationWithDifferentReturnValues()
{
    $this->mock->shouldReceive('foo')->andReturn('green', 'blue');
    $this->assertEquals($this->mock->foo(), 'green');
    $this->assertEquals($this->mock->foo(), 'blue');
    $this->assertEquals($this->mock->foo(), 'blue');
}
```

If possible, I use with() and once() to make sure a test isn't passing by accident.

**Comment by jdunk** [comment]
@fhinkel I appreciate what you're saying, but this still requires modifying the original expectation-setting statement.  Imagine you have a test suite, and you want to set a default expectation in an initializer function that is called for every test, and then for only one or a few tests, a different expectation is desired.  Assuming what aik099 says is true, the ->byDefault method is the only current known way to override an expectation statement that has already been executed.

**Comment by spronkey** [comment]
For what it's worth, I agree with jdunk. I'd say the order should be reversed - i.e. it should match the latest expectation first, especially for stubs. At the very least, you should be able to configure.

This is where having an API for inspecting the calls made to the mock would be really handy - i.e. instead of setting up expectations beforehand, assert on them after i.e.

    $calls = $mock->callsTo('method');
    $this->assertEquals($calls->count(), 2);
    $this->assertTrue($calls[0]->argument(1)->match(...));

**Comment by kirkbushell** [comment]
@spronkey - that's what spies are for, which are already in the project.

**Comment by spronkey** [comment]
@kirkbushell oh? I didn't even know. The docs don't mention that at all!

**Comment by kirkbushell** [comment]
@spronkey yeah it's only on the master branch, I think. Here: http://davedevelopment.co.uk/2014/10/09/mockery-spies.html

**Comment by kirkbushell** [comment]
It's really great for writing unit tests for things like command handlers, which are usually just a stack of object calls with very little logic themselves.

**Comment by deanbolton** [comment]
For anyone else who encounters this issue, the underlying problem has since been resolved. 

Instead of adding the `->byDefault()` to your overriding `shouldReceive` call (as mentioned above many years ago), add it to your initial call. For example, using the OP's example:

```
protected function setUp(): void
{
    parent::setUp(); 
    $this->mock->shouldReceive('foo')->andReturn('green')->byDefault();
}

public function testExpectationCanBeOverridden()
{
    $this->mock->shouldReceive('foo')->andReturn('blue');
    $this->assertEquals($this->mock->foo(), 'blue');
}
```

Both ways will work, but this way seems more logical. Reference: https://github.com/mockery/mockery/issues/783
