### ISSUE TITLE
Argument validation with boolean true

### ISSUE THREAD

**Issue by bramstroker** [padraic/mockery#409]
When I setup a argument validation on my method phpunit will pass the test when I call the method with the boolean `true`.

**This test succeeds as expected:**

    $myMock->shouldReceive('setFoo')->with('baz')->once();
    $myMock->setFoo('baz');

**This test succeeds (expect a failure):**

    $myMock->shouldReceive('setFoo')->with('bar')->once();
    $myMock->setFoo(true);

**This test fails as expected:**

    $myMock->shouldReceive('setFoo')->with('bar')->once();
    $myMock->setFoo('baz');

**This test also succeeds (expect a failure here as well):**

    $myMock->shouldReceive('setFoo')->with(true)->once();
    $myMock->setFoo('bar');

**Comment by aik099** [comment]
This is because comparison is done using `==` and not `===`. You should use `m:: mustBe(true)` instead of just `true` in this case.

**Comment by bramstroker** [comment]
@aik099, already thought it had to do with typesafe comparison. thanks it is working as expected now.

**Comment by aik099** [comment]
You're welcome.
