### ISSUE TITLE
is there a way to access mocked object method arguments values?

### ISSUE THREAD

**Issue by programmador** [padraic/mockery#410]
For example, I'm mocking the next class:
```
class MyClass {
  myMethod($arg1, array $arg2) { /*do smth*/ }
}
```
In Laravel framework, using facades, I have to mock it this way:
```
public function testSmth() {
    MyClass::shouldReceive('myMethod')->andReturn('blah blah blah')->andSoOn();
}
```
How can I get arguments, which are propagated to `myMethod`? In my case the arguments are quite complex objects, and I want to compare some of their fields to database entries.

I tried smth like this:
```
MyClass::shouldReceive('myMethod')->andReturn('')
    ->with(Mockery::on(function($arg1, array $arg2) {
        // Read $arg1 and $arg2 here and do anything I want with them
         return true;
    }));
```
but it just always thows `NoMatchingExpectationException`, and no matter whether I return true or false from closure;

Looks like Mockery tries to mock `$arg1` and `$arg2` somehow - sometimes I see messages like this:
```
'getPaginator' => '!! BadMethodCallException: Method Mockery_1_Illuminate_View_Factory::addNamespace() does not exist on this mock object !!',
```
in the traceback. where` getPaginator` may be a method of `$arg1` object. Or a method of any object of array `$arg2`.

Maybe I understand smth wrong, especially Mockery::on() and with() purpose.

**Comment by davedevelopment** [comment]
I do it this way

``` php
MyClass::shouldReceive('myMethod')->andReturnUsing(function($arg1, array $arg2) {
    // Read $arg1 and $arg2 here and do anything I want with them
    return 'blah blah blah';
});
```

**Comment by programmador** [comment]
Oh, thank's a lot! It works!
