### ISSUE TITLE
is there method like phpunit's at method in mockery?

### ISSUE THREAD

**Issue by dbwhddn10** [padraic/mockery#411]
is there method like phpunit's at method in mockery?

i want implement like below link with mockery

http://www.andrejfarkas.com/2012/07/phpunit-at-method-to-check-method-invocation-at-certain-index/

**Comment by aik099** [comment]
You mean to a return value to be different depending on which call to the method is it?

Yes, you can do `->andReturn('on 1st call', 'on 2nd call', 'on other calls')`.

**Comment by dbwhddn10** [comment]
i want to check method execute order

**Comment by dbwhddn10** [comment]
@aik099  thank you reply.

i want to check method execute order

like this
```
$mock->at(1)->shouldReceive('firstMethod')->once();
$mock->at(2)->shouldReceive('secondMethod')->once()
```

```php
// no error
$mock->firstMethod();
$mock->secondMethod();
```

```php
// error and throw exception
$mock->secondMethod();
$mock->firstMethod();
```

**Comment by dbwhddn10** [comment]
i want mockery's ordered method

**Comment by aik099** [comment]
That what I was writing, yes: http://docs.mockery.io/en/latest/reference/expectations.html?highlight=ordered
