### ISSUE TITLE
Typo in project description

### ISSUE THREAD

**Issue by WebnetMobile** [padraic/mockery#413]
Not really a code issue but your project description reads: `[...] framework with a succint API capable [...]`. The correct word is `succinct` though.

**Comment by aik099** [comment]
Thanks for noticing. Could you please send a PR with a fix.

**Comment by WebnetMobile** [comment]
I am not sure this would solve the problem. I.e. your README.md uses correct `succinct` but your project description (which is not part of repo) is incorrect. Also you use wrong spelling in other places too, i.e.https://packagist.org/packages/mockery/mockery

**Comment by WouterJ** [comment]
The spelling on packagist can be changed by changing the description value in `composer.json`. The project descriptions can only be changed by owners, which I think is only @padraic (since this is not an organization).

**Comment by WebnetMobile** [comment]
I sent pull request https://github.com/padraic/mockery/pull/414

**Comment by WebnetMobile** [comment]
Fixed in

**Comment by padraic** [comment]
Totally embarrassed right now. Thanks for the PR, not so much for noticing ;).

**Comment by ifeltsweet** [comment]
Just a heads up, the typo is still there, in the Github project description.
