### ISSUE TITLE
how to mock parent::xxx method

### ISSUE THREAD

**Issue by dbwhddn10** [padraic/mockery#418]
is there a way?

```php
class AAA extends BBB {
    public function ccc()
   {
       parent::ccc();
   }
}
```

I want to check parent ccc method 1 time called

**Comment by aik099** [comment]
Not sure. Mockery replaced whole method body with `__call` method, so partial method body isn't possible.

**Comment by fhinkel** [comment]
You can use an instance mock to test that BBB::ccc() was called. 
```
public function testParentCCCWasCalled()
{
    $mock = Mockery::mock('overload:BBB');
    $mock->shouldReceive('ccc')->once();

    $aaa = new AAA();
    $aaa->ccc(); 
}
```

**Comment by dbwhddn10** [comment]
@fhinkel thank you so much!!
