### ISSUE TITLE
Mockery does not provide integration with PHPUnit

### ISSUE THREAD

**Issue by Bilge** [padraic/mockery#424]
PHPUnit has a test mode designed to "[report useless tests](https://phpunit.de/manual/current/en/strict-mode.html)" which marks tests that do not perform any assertions or expectations. However, PHPUnit is ignorant to any expectations performed on Mockery objects since Mockery has no integration with PHPUnit.

**Comment by davedevelopment** [comment]
We have the [MockeryTestCase](https://github.com/padraic/mockery/blob/master/library/Mockery/Adapter/Phpunit/MockeryTestCase.php) which I believe helps with this

**Comment by aik099** [comment]
@davedevelopment is correct. Due restrictions of PHPUnit test listeners (which default Mockery integration mode with PHPUnit) it's unable to properly report such tests.

**Comment by Bilge** [comment]
Wouldn't it be better implemented as a trait?

**Comment by aik099** [comment]
There is a trait already if I'm not mistaken, but projects which use PHP 5.3 are unable to use it and that's why there is also abstract test case class.

**Comment by davedevelopment** [comment]
There's no trait at this time, we're still supporting 5.3 and I'm not overly keen on the idea of using traits for this kind of extension.

**Comment by Bilge** [comment]
Introducing an optional trait does not relinquish support for 5.3.

**Comment by davedevelopment** [comment]
@Bilge, no but we'd need to copy-paste any changes to both the trait and the abstract class in the mean time. I'm not against a trait, but I personally wouldn't use it

**Comment by Bilge** [comment]
That doesn't surprise me. From the way you're acting you've never harnessed horizontal reuse in your life.

**Comment by davedevelopment** [comment]
@Bilge if you would like a trait, please submit a PR and I'll happily merge it, but please don't insult me, thanks.

**Comment by Bilge** [comment]
I just wanted you to be aware of your xenophobic attitude.

**Comment by davedevelopment** [comment]
@Bilge okay, thanks.

**Comment by Bilge** [comment]
It was never my intention to insult you :+1:

I'm considering submitting a PR soon, but even if it were accepted, this issue would not be resolved. My impression was that there was no attempt made to solve this issue, and yet there is, which is an outstanding documentation issue unless you can show me the part of the documentation that describes this class that I missed.

**Comment by davedevelopment** [comment]
No, there are no docs yet, the only acknowledgement of it's existence is in the changelog. I'm well behind on the docs. Labelled this one as a documentation issue and look forward to your PR.

**Comment by Bilge** [comment]
Surely the correct thing to do would be to just use [TestListener](https://github.com/padraic/mockery/blob/master/library/Mockery/Adapter/Phpunit/TestListener.php). I'm not really sure why MockeryTestCase even exists. Previously I did not realise PHPUnit could be extended in this fashion but this seems like a much more elegant solution than a base class *or* a trait.

**Comment by aik099** [comment]
As I said before the test case exists due limitations (from PHPUnit side) on what test listener can do. For example test listener can't add up make assertions to prevent `tests without assertions` error in strict mode.

**Comment by davedevelopment** [comment]
Yes, the test listener work for a long time, but it was a hack. See sebastianbergmann/phpunit#1440

**Comment by Bilge** [comment]
Seems like another of Bergmann's half-baked ideas. I can't see the point in implementing a plugin architecture that's read-only. Nevertheless I finished the trait and will create a PR shortly.

**Comment by padraic** [comment]
PHPUnit isn't namespaced so it will take a lot to see it opened up for crazy extensions. If they implemented good dependency injection it would be really simple to integrate with it. At the moment, you can do certain hacks by employing reflection to force certain properties from private/protected into public readable though I'm not sure if that's a path we'd want to go down...

Yes, I am alive.

**Comment by davedevelopment** [comment]
Captain on the bridge!

**Comment by padraic** [comment]
Actually, it's Admiral now ;) That's when you take extended vacations and let some other poor soul run the bridge. Thanks for that ;)

**Comment by padraic** [comment]
@Bilge Reading Sebastian's comments on the original issue, the response to use a subclass is disingenuous. It creates an additional barrier to things like Mockery to expect users to use a special subclass (which creates a web of optional hard deps) as opposed to a proper plugin/extension which should be an invisible once off config option where proper DI is used.

**Comment by Bilge** [comment]
@padraic He has a habit of blowing off reasonable issue reports too quickly. Hopefully the trait can stand in place of a subclass until a better solution is possible.

**Comment by padraic** [comment]
We'll see, I know Sebastian was suggesting moving the PHP supported version up significantly recently so maybe that will see some work being done in the internals.

**Comment by davedevelopment** [comment]
I think with the integrated support for prophecy in 4.5, he wont be too inclined to make changes to help support us.

**Comment by padraic** [comment]
@davedevelopment Or anyone else ;). I'm using listeners to manipulate tests (a write op) for Humbug. There are also a few other extensions doing same to offer memory cleanup and improve performance. The whole "listeners are read only" line is farcical when these no obvious "writeable" extension point.

**Comment by aik099** [comment]
> https://github.com/padraic/mockery/issues/424#issuecomment-74231673

@davedevelopment , PHPUnit is replacing own mocking solution with Prophecy, are you certain?

**Comment by aik099** [comment]
> The whole "listeners are read only" line is farcical when there's no obvious "writeable" extension point.

@padraic , completely agree. I doubt that it would take much effort to move listener triggering code a bit to allow write operation is that much of a problem.

**Comment by davedevelopment** [comment]
@aik099 not replacing, phpunit mocks provide some of the more exotic features (like we do) that prophecy specifically wont provide, so they'll be there to stay for now. You read more here http://thephp.cc/news/2015/02/phpunit-4-5-and-prophecy, TLDR; you can do this in your test methods:

```
$prophecy = $this->prophesize("SomeType");
$double = $prophecy->reveal();
```

**Comment by davedevelopment** [comment]
@padraic yeah, if the listeners were meant to be read only, they should have enforced that somehow, but hey ho.

**Comment by Bilge** [comment]
People will still vote with their feet.

**Comment by aik099** [comment]
Any idea, why Prophecy was chosen over Mockery?

**Comment by davedevelopment** [comment]
@aik099 prophecy is very good and offers something different to phpunit mocks. They have a very active and talented team behind it, backed by a very active and respected company who offer lots of training and consulting.

**Comment by padraic** [comment]
@aik099 All I saw was a comment that Sebastian considered prophecy more mature. I wouldn't read too much into it. Using test doubles can be very opinionated over even minor variances in usage patterns and language. Most programming languages out there have 3+ various libraries doing the rounds at any given time. Ruby's are currently rspec, rr, mocha and flexmock. PHP has mockery, prophecy, aspectmock and a few others.

I seriously doubt any of them are bad, and I'm practical. It's a win purely to have phpunit pushed into supporting anything other than it's traditional mocks.

Anyone have a "Victory" banner? :P

**Comment by Bilge** [comment]
>backed by a very active and respected company who offer lots of training and consulting

i.e. he was probably paid.
