### ISSUE TITLE
`times()` expectation not working -- always passes 

### ISSUE THREAD

**Issue by heldtogether** [padraic/mockery#426]
The `times()` expectation is being ignored. If the expectation is set to 0 and the method is called, it passes. If the expectation is set to 1 and the method is never called, it passes.

```php
<?php

class TestCase extends PHPUnit_Framework_TestCase {

	/**
	 * Test Zero Times Assertion
	 */
	public function testZeroTimesAssertions() {

		$foo = Mockery::mock('foo');
		$foo->shouldReceive('bar')
		    ->times(0);

		$foo->bar();

	}

	/**
	 * Test One Times Assertion
	 */
	public function testOneTimesAssertions() {

		$foo = Mockery::mock('foo');
		$foo->shouldReceive('bar')
		    ->times(1);

	}

}
```

```
$ phpunit
PHPUnit 4.3.0 by Sebastian Bergmann.

..

Time: 66 ms, Memory: 3.50Mb

OK (2 tests, 0 assertions)
```

**Comment by davedevelopment** [comment]
Hey there, are you using the PHPUnit test listener? If not you'll either need to use it, manually call `Mockery::close()` or use the new MockeryTestCase. The first two are detailed in the docs http://docs.mockery.io/en/latest/reference/phpunit_integration.html and the latter can be done by:

``` php
<?php

use Mockery\Adapter\Phpunit\MockeryTestCase;

class TestCase extends MockeryTestCase {
// your usual test code

```

**Comment by heldtogether** [comment]
Ah right, missed that bit!

This ticket is invalid then.

**Comment by davedevelopment** [comment]
No problem!

**Comment by kminh** [comment]
@davedevelopment `MockeryTestCase` seems to be the only thing that works for me when I use PHPUnit's `@runInSeparateProcess` annotation. Neither `Mockery::close()` nor the listener seems to work for `times()`, `once()`, etc.

**Comment by davedevelopment** [comment]
@kminh open an issue with a sample test and I'll see if I can take a look. I'd recommend using the `MockeryTestCase` or the equivalent trait anyway.
