### ISSUE TITLE
[RFC] End PHP 5.3 Support

### ISSUE THREAD

**Issue by padraic** [padraic/mockery#432]
As we've recently adopted a trait, it's a reminder that we are limited in what language features can be used going forward. PHP 5.3 is EOL. Symfony, Zend Framework and PHPUnit are all likely to shift to at least PHP 5.4 (or later) quite rapidly towards end of year in their next major versions. As a concerted effort, this will likely push us into a spillover such as we saw with adopting PHP 5.3 as the high standard some years ago.

I would propose making it known that Mockery 0.9.4 will be the final Mockery version offering guaranteed PHP 5.3 compatibility subject to any last ditch feature addition where using PHP 5.4 is clearly silly talk ;). Thereafter we should be free to use any PHP 5.4 features without restraint in the run up to a 1.0.0 release.

It's probably noteworthy that PHP is now on a rapid release schedule. PHP 5.4 will go EOL relatively soon also. PHP 5.5 a year thereafter, and so on.

**Comment by robertbasic** [comment]
FWIW, we're running php 5.6 and mockery successfully on production since, well, 5.6 came out.

**Comment by davedevelopment** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
:+1: for shifting to 5.4+. I think keeping at 5.4+ and not 5.5+ would be a better idea for now, since many people using mockery still need to support php 5.4.

**Comment by padraic** [comment]
@davedevelopment I'll document this on the README. I'd propose tagging a new release before end March and then we can flip the requirement to PHP 5.4 in master.

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by padraic** [comment]
Documented in README
