### ISSUE TITLE
[RFC] Closing PEAR Channel

### ISSUE THREAD

**Issue by padraic** [padraic/mockery#433]
This is probably an obvious one. The pear channel has seen no new releases and won't any time soon. I'd like to announce a shutdown over 2015 so anyone still dependent on it can migrate to composer and the new Mockery releases since 0.9.0.

**Comment by davedevelopment** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by aik099** [comment]
:+1:

**Comment by robertbasic** [comment]
+1

**Comment by robertbasic** [comment]
Should add a note into the docs here http://docs.mockery.io/en/latest/getting_started/installation.html#pear to not use the pear channel any more as it is going to be shut down. Or just remove that part completely?

**Comment by padraic** [comment]
I would add a dated deprecation, and kill it when it times out.

Anyone have timing suggestions? I can give as long as folk need within reason.

**Comment by davedevelopment** [comment]
A month? Two months? Until it goes down again? ;)

**Comment by padraic** [comment]
Will add to README later providing a shutdown date of approximately 30 June 2015. Assuming I remember, or the server doesn't self-destruct around that time all without assistance ;).

**Comment by padraic** [comment]
Documented in README
