### ISSUE TITLE
ErrorException: Missing argument 1 When mocking only Guzzle\Http\Client

### ISSUE THREAD

**Issue by janakassm** [padraic/mockery#455]
Hi, I'm trying to mock 'Guzzle\Http\Client' object. But when I mock as follows
```
$mock = m::mock('Guzzle\Http\Client');
$mock->shouldReceive('send')
                ->once()
                ->andReturn( false );
```
And my test failes with "ErrorException: Missing argument 1 for Mockery_0_Guzzle_Http_Client::send(), called ...."

The funny thing is, if i mock
```
$mock = m::mock('TestClient');
$mock->shouldReceive('send')
                ->once()
                ->andReturn( false );
```
This passes.

Does anyone know why its happening and how to fix it?

Thanks

**Comment by aik099** [comment]
When defining an expectation on the mock you need to pass values for all optional parameters as well. If you don't care about what's actually passed then `->with(m::any())` would be fine. I presume the `send` method has 1 optional parameter.

**Comment by janakassm** [comment]
Yes, you are correct send( array|Guzzle\Http\Message\RequestInterface $requests ) is expecting an parameter. Your answer pointed me in the right direction.

I was mocking the wrong class method after all. I should have mock the Guzzle\Http\Message\Request calss which get returned after calling Guzzle\Http\Client::post(). Dumb mistake.

Thanks for the quick reply @aik099

**Comment by aik099** [comment]
You're welcome.
