### ISSUE TITLE
Constructor with empty (using defaults) arguments is not able to call methods

### ISSUE THREAD

**Issue by havvg** [padraic/mockery#460]
This (see #144, #145) does not work, if the constructor calls methods internally.

```php
// BadMethodCallException : Method Mockery_0_Symfony_Component_HttpFoundation_Request::initialize() does not exist on this mock object
// (initialize being public method called within constructor)
$request = \Mockery::mock('Symfony\Component\HttpFoundation\Request', []);
$request->shouldDeferMissing();
```

Workaround - at least for the Request class in the example. However, this requires insight of any changes to the class, which is bad.

```php
$request = \Mockery::mock('Symfony\Component\HttpFoundation\Request'); // does not call __construct.
$request->shouldDeferMissing();
$request->initialize(); // The only thing, __construct actually does.
```

**Comment by aik099** [comment]
Does this work?
```php
$request = \Mockery::mock('Symfony\Component\HttpFoundation\Request', [])->makePartial();
```

**Comment by havvg** [comment]
Nope. It fails before reaching `makePartial`.

**Comment by davedevelopment** [comment]
Can you get around it by making a generation time partial? It's not ideal as you'll need to list other methods upfront as well, but might get you somewhere. 

``` php
$request = m::mock("Symfony\Component\HttpFoundation\Request[initialize]", []);
```

Otherwise, it's a narrow use case for me and I personally wouldn't look to try and support it in Mockery.

**Comment by havvg** [comment]
Well it's not working, also tried '[]'. However, `$this->request = \Mockery::mock(new Request());` works fine, so I will go with this one.
