### ISSUE TITLE
PHP Parse error - MockingVariadicArgumentsTest.php on line 52

### ISSUE THREAD

**Issue by MaiKaY** [padraic/mockery#465]
Hi guys, 
since the version 0.9.4 i got the following error while building my project.

> [...]/vendor/mockery/mockery/tests/Mockery/MockingVariadicArgumentsTest.php
[apply] PHP Parse error:  syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in [...]vendor/mockery/mockery/tests/Mockery/MockingVariadicArgumentsTest.php on line 52

[Link to the file](https://github.com/padraic/mockery/blob/master/tests/Mockery/MockingVariadicArgumentsTest.php#L52)

Can you please have a look into this issue?

Best regards
MaiKaY

**Comment by aik099** [comment]
That test requires PHP 5.6 it seems (due variadic function parameter usage). Then you must be using lower PHP version.

Maybe PHPUnit can be told to skip that test if PHP version is lower then 5.6, because at file opening time you'll immediately get parsing error.

**Comment by davedevelopment** [comment]
That test should be skipped when running mockery's test suite, unless you're using a custom phpunit config file. If you're running your own test suite, I think you'll maybe need to check to see if you're trying to generate coverage etc, as that may lead to the file being included for analysis etc.

**Comment by MaiKaY** [comment]
Thanks guys for the fast answers!
I will close this "issue" & check my dependencies ;-)
