### ISSUE TITLE
overload problem

### ISSUE THREAD

**Issue by dbwhddn10** [padraic/mockery#466]
```php
   public function TestAAAA()
   {
      $class = m::mock('overload:ClassPath');
   }

   public function TestBBBB()
   {
      $class=m::mock('ClassPath'); // error : cannot redeclare 'classPath::mockery_init() in ~~~
   }
```

how to fix this problem?

**Comment by aik099** [comment]
I guess you can't overload same class twice.

**Comment by davedevelopment** [comment]
I'd run that test in a [separate process](https://phpunit.de/manual/current/en/appendixes.annotations.html#appendixes.annotations.runInSeparateProcess)


``` php
    /**
    * @runInSeparateProcess
    */
   public function TestAAAA()
   {
      $class = m::mock('overload:ClassPath');
   }
```

**Comment by robertbasic** [comment]
This is documented in the cookbook entry http://docs.mockery.io/en/latest/cookbook/mocking_hard_dependencies.html

**Comment by dbwhddn10** [comment]
@aik099 , @davedevelopment , @robertbasic thanks
