### ISSUE TITLE
i keep getting instance of Mockery_0__*, why ?

### ISSUE THREAD

**Issue by OussamaDEV** [padraic/mockery#467]
i want to mock a class called Holla does not exist .. 

<?php   namespace App;

class Temp {

    public function __construct(Holla $holla)
    {
        $this->holla = $holla;
    }

    public function greet()
    {
        return $this->holla->say();
    }
}

and this is the test for Temp class

<?php

use App\Temp;

class HollaTest extends PHPUnit_Framework_TestCase {

    public function testICanGreet()
    {
        $holla = Mockery::mock('Holla');
        $holla->shouldReceive('say')->once()->andReturn('hi');

        $temp = new Temp($holla);
        $this->assertEquals('hi', $temp->greet());
    }
}

when i run the test i get:

PHPUnit 4.6.4 by Sebastian Bergmann and contributors.

E

Time: 123 ms, Memory: 3.25Mb

There was 1 error:

1) HollaTest::testICanGreet
Argument 1 passed to App\Temp::__construct() must be an instance of App\Holla, instance of Mockery_0__Holla given, called in /home/oussama/Desktop/iLearn/iLearnToMock/tests/HollaTest.php on line 13 and defined

/home/oussama/Desktop/iLearn/iLearnToMock/app/Temp.php:6
/home/oussama/Desktop/iLearn/iLearnToMock/tests/HollaTest.php:13
phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:186
phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:138
                                   
FAILURES!                          
Tests: 1, Assertions: 0, Errors: 1.

shell returned 2

Press ENTER or type command to continue

i tryed a lot of combinations and examples, but i get the same error, also i tried to dive into the source code, but once i get to Container::mock() it was too long (not profiled), and i don't really have time to track the issue.

any idea, why am getting this, or at least a heads up on where or where should i go to resolve this issue.

**Comment by davedevelopment** [comment]
``` php
$holla = Mockery::mock('App\Holla');
```

?

**Comment by OussamaTheDev** [comment]
@davedevelopment actually it pass (test is green), can you please explain to me why?

i spend more than 3hours with this problem, i think i deserve some explanation, and why Mockry didn't just throw a helpful error ?

**Comment by padraic** [comment]
```
Argument 1 passed to App\Temp::__construct() must be an instance of App\Holla
```
Message seems fairly helpful, it needs an instance of that type so that's the type to ensure you mock. It looks like you passed in a class name without the namespace.

**Comment by davedevelopment** [comment]
Pretty much what @padraic says, I'd only add that there's not a whole lot Mockery can do at that point, other than registering our own error handler and that would be very messy.

**Comment by OussamaDEV** [comment]
@padraic yep, that's my mistake, when i saw instance of App\Holla i was thinking about the real object, which actually doesn't exist at all. then i notice after @davedevelopment that i should consider the one inside the class i want to test.

i've write about it here http://devgol.com/blog/improve-your-tests-by-mocking-objects/
thank you.

**Comment by GrahamCampbell** [comment]
@OussamaDEV On your're blog you've put phpunit and mockery in require when they should be in require-dev.

**Comment by GrahamCampbell** [comment]
Also, you should never use a wildcard version constraint.

**Comment by OussamaDEV** [comment]
@GrahamCampbell thank you i will fix that, for the wild card i just wanted to pull the latest, and actually i've found a little bug in phpunit am gonna report it later.

**Comment by GrahamCampbell** [comment]
> for the wild card i just wanted to pull the latest

That still makes no sense. PHPUnit 5 could totally break your code if if it's namespaced.

**Comment by OussamaDEV** [comment]
@GrahamCampbell fixed - thank you

**Comment by padraic** [comment]
Closing issue as it appears to be resolved.
