### ISSUE TITLE
Calling a degenerative `->with()`

### ISSUE THREAD

**Issue by vizath** [padraic/mockery#468]
Hello,
I have a test that checks that a method has been called with some specific arguments. Each argument must be passed only once.
Here's the failling test case:

```php
public function testBug() {
	$expectedZipNames = ['name1', 'name2', 'name3'];

	$zip = \Mockery::mock('zip', function($mock) use (&$expectedZipNames) {
		$mock->shouldReceive('getFromName')
			->times(2)
			->with(\Mockery::on(function($argument) use (&$expectedZipNames)  {
				// check if the argument is in the valid list, and remove it to not be able to validate it again.
				if (($key = array_search($argument, $expectedZipNames)) !== false) {
					array_splice($expectedZipNames, $key, 1);
					return true;
				}
				return false;
			}))
			->andReturn(false);
	});

	$zip->getFromName('name1');
	$zip->getFromName('name2');
	// The error show should be
	// Mockery\Exception\InvalidCountException:
	// 		Method getFromName(object(Mockery\Matcher\Closure)) from Mockery_0__zip
	// 		should be called exactly 2 times but called 3 times.
	// but I get
	// Mockery\Exception\NoMatchingExpectationException:
	// 		No matching handler found for Mockery_0__zip::getFromName("name3").
	// 		Either the method was unexpected or its arguments matched no expected argument list for this method
	$zip->getFromName('name3');

	$this->assertCount(0, $expectedZipNames);
}
```

I think that it can be fixed by changing ExpectationDirector@_findExpectationIn
https://github.com/padraic/mockery/blob/master/library/Mockery/ExpectationDirector.php#L173
`if ($exp->matchArgs($args) && $exp->isEligible()) {`
to
`if ($exp->isEligible() && $exp->matchArgs($args)) {`
but I do not know all the underlying implications.

Thanks.

**Comment by davedevelopment** [comment]
I'm not sure either! I can't think of anything off the top of my head, perhaps try changing it and running mockery's test suite?

**Comment by padraic** [comment]
@vizath I've no idea off hand. Switch the order of the statements, and run the unit tests. If they all pass, and it resolves your problem, you can open a PR and we'll take it into consideration as a fix for this particular scenario.
