### ISSUE TITLE
Troubles with demeter chains

### ISSUE THREAD

**Issue by leordex** [padraic/mockery#477]
When I use Mockery for mocking a chain like that:
```php
$model->shouldReceive('table_files_thumbs->insert')
            ->andReturn(ErrorCodes::ERROR_DEV_SQL_INSERT)
            ->once()
            ->getMock();
$result = $img->get(1, ['company_preview']);
        $this->assertNull(
            $result->data,
            'Insert thumbs data check failed in the function `Img->get`'
        );

        $model->shouldReceive('table_files_thumbs->insert')
            ->andReturn(ErrorCodes::ERROR_EMPTY)
            ->getMock();
```
Sometimes I get the error ERROR_DEV_SQL_INSERT from the first calling of Mockery, i.e. once() is not working. Is that normal behaviour?

**Comment by davedevelopment** [comment]
The `once` isn't "return this data once", it's "I only expect this to method to be called once". 

You probably want this:

``` php
$model->shouldReceive('table_files_thumbs->insert')
            ->andReturn(ErrorCodes::ERROR_DEV_SQL_INSERT, ErrorCodes::ERROR_EMPTY)
            ->getMock();
```

That reads as return `ErrorCodes::ERROR_DEV_SQL_INSERT` on the first call, then `ErrorCodes::ERROR_EMPTY` on the second call.

**Comment by leordex** [comment]
Thanks, looks like I didn't paid enough attention to documentation.
