### ISSUE TITLE
The use statement with non-compound name 'Mockery' has no effect

### ISSUE THREAD

**Issue by miertschink** [padraic/mockery#478]
I just upgraded to PHP Version 5.5.26 and now getting this warning:

    The use statement with non-compound name 'Mockery' has no effect in .../vendor/basekit/phpunit-extensions/PHPUnit/Extensions/Mockery/TestCase.php on line 10

changing this line to
use \Mockery as Mockery;

fixes the problem.
Is this a php-bug or does Mockery need an update?

**Comment by GrahamCampbell** [comment]
That's not correct...

**Comment by miertschink** [comment]
could you please be a little bit more specific?
what`s not correct?

**Comment by GrahamCampbell** [comment]
You don't need to import it at all.

**Comment by miertschink** [comment]
ah - damn
ok - you are right this seems to be not the right repository
The code I was using comes from the basekit/phpunit-extensions
https://github.com/basekit/phpunit-extensions/blob/master/PHPUnit/Extensions/Mockery/TestCase.php

Seems to be not maintained. I will open an issue there
Thank you

**Comment by GrahamCampbell** [comment]
As I said, you don't need the import.

**Comment by GrahamCampbell** [comment]
Then it will work.

**Comment by miertschink** [comment]
yes
I will try to switch to the etsy/phpunit-extensions
https://github.com/etsy/phpunit-extensions/blob/v0.7.0/PHPUnit/Extensions/Mockery/TestCase.php

there is no import
Thanks
