### ISSUE TITLE
My /tmp is filled with mockery files, what am I missing?

### ISSUE THREAD

**Issue by marcaube** [padraic/mockery#487]
It seems a *temporary* file is generated (e.g. `/tmp/MockeryvAahXH`) in [ClassPass](https://github.com/padraic/mockery/blob/master/library/Mockery/Generator/StringManipulation/Pass/ClassPass.php#L36) for each class mocks. The problem I have is that they are never deleted.  There's tens of thousands of them.

My test classes extend `\Mockery\Adapter\Phpunit\MockeryTestCase`, am I missing something? Do I still need the `tearDown()` method or the listener?

**Comment by davedevelopment** [comment]
I think creating a file is a necessary evil there, but ideally it's a narrow use case, that should only happen whenever the class you are trying to mock doesn't actually exist or at least can't be found by autoloading. 

I'd be happy to merge something that attempts a clean up on shutdown or something.

**Comment by marcaube** [comment]
Ah! well, that is exactly my case. Some of the classes that are mocked do not exist in the test context. They are autoloaded deep inside a legacy system, and the unit tests steer clear of that bootstrap.

If I were to code something for this, how should I tackle the problem? Keep track of all the temporary files in an array somewhere and unlink them during shutdown?

**Comment by davedevelopment** [comment]
> If I were to code something for this, how should I tackle the problem? Keep track of all the temporary files in an array somewhere and unlink them during shutdown?

Yeah I think that would do it. You could hook it in to `\Mockery::teardown`, that will probably be cleaner than trying to use php's `register_shutdown_function`.

``` php 
// in ClassPass
\Mockery::registerFileForCleanUp($tmpfname);

// in Mockery::tearDown
foreach (static::$filesForCleanUp as $filename) {
    @unlink($filename);
}
```

**Comment by marcaube** [comment]
Thanks, I'll try to come up with a tested solution before the end of the week. I love That Podcast BTW.

**Comment by GrahamCampbell** [comment]
> 
// in Mockery::tearDown

Why not just have mockery do this in it's destructor?

**Comment by marcaube** [comment]
You mean in `Mock::__destruct()`?

**Comment by aik099** [comment]
> I love That Podcast BTW.

What podcast?

**Comment by davedevelopment** [comment]
@GrahamCampbell I'd prefer the explicit over implicit.

@aik099 *That Podcast* (thatpodcast.io)

**Comment by GrahamCampbell** [comment]
> You mean in Mock::__destruct()?

No. PHP calls that for you whenever an object is being deleted.

**Comment by aik099** [comment]
Not exactly. The method is called, when object is garbage collected. Not sure if related, when when I was xdebugging the code the `__destruct` method was called only sometimes, when script finished. That's why something that will be called in any case, like `Mockery::tearDown` is more preferred.

**Comment by GrahamCampbell** [comment]
> Not exactly. The method is called, when object is garbage collected. 

Yeh, so when the object is being deleted from memory. :)
