### ISSUE TITLE
Alias mocks with constants on the class

### ISSUE THREAD

**Issue by iainfogg** [padraic/mockery#491]
I read the issue at https://github.com/padraic/mockery/issues/443 and think this is slightly different, hence the new issue.

I have a class which has some static methods on that I wish to mock out. So, following the notes here http://docs.mockery.io/en/latest/reference/public_static_properties.html I have this code:

        $mockAPI = Mockery::mock('alias:MyClassName');
        $mockAPI->shouldReceive('myMethod')->once();

That works fine, and calls to myMethod go to the mock instead of to the actual class.

However, I also have a line which uses:
```
MyClassName::C_SOME_CONSTANT
```

This line fails with the error:
```
Undefined class constant 'C_SOME_CONSTANT'
```

Presumably this is because the constant is on the actual class, and the alias doesn't have them, and doesn't pass them through in any way.

Is there any way for me to benefit from using aliases to intercept static methods, but to also have access to the class's constants? Without this, I can't test my existing legacy code.

Thanks!

**Comment by augusteiner** [comment]
+1

**Comment by davedevelopment** [comment]
There isn't an easy way. Mockery can't autoload your original class to look for constants, it would have to find the file, parse it for constants and add them to the class it generates to provide the double functionality.

We could add something that would allow you to define some class constants.

Alternatively, you could do some wrangling yourself:

``` php
class ClassConstantStub
{
    const C_SOME_CONSTANT = 123;
}

$mock = Mockery::namedMock('MyClassName', 'ClassConstantStub');
```

That might work, haven't tried it though.

**Comment by iainfogg** [comment]
Thanks @davedevelopment - I had thought that because in other scenarios, Mockery is able to defer to the original object, there would be some way to find the original values. 

Alternatively, because I can redefine methods on the mock with shouldReceive, I thought I might be able to add constants in the same way, but that never worked. It would make sense if there were some way to be able to add them manually, even if it's not possible to auto-discover them, because without that feature, it becomes impossible to test an alias which has constants without reworking the code being tested.

I tried the example you suggested, but it crashes with:

Call to undefined method MyClassName::mockery_init() 
in /Volumes/Sources/cap/hope/vendor/mockery/mockery/library/Mockery/Container.php:222

**Comment by davedevelopment** [comment]
Huh, this definitely works for me

``` php
<?php

require "vendor/autoload.php";

class ClassConstantStub
{
    const C_SOME_CONSTANT = 123;
}

$mock = Mockery::namedMock('MyClassName', 'ClassConstantStub');

var_dump(MyClassName::C_SOME_CONSTANT); // int(123)
```

Adding the constants wouldn't be a quick job and it would require the user of the builder, I don't think we could fit it in to the usually nice `Mockery::mock` god method thing.

**Comment by iainfogg** [comment]
Thanks @davedevelopment - my first class is an alias, is that why we're getting different responses?

The scenario is I am trying to intercept a call to a static method on a class buried several layers down through some procedural legacy code where the method sends out text messages, as I don't want the texts sending during my testing. Because the class is not injected in, and because it's a static method like MyClassName::sendText, I need to use the alias (unless there's another way you can suggest?) to intercept it. I've not found another way to intercept that call. But using the alias is where the constant then becomes inaccessible.

Am I approaching this the wrong way?

**Comment by davedevelopment** [comment]
Because I'm using a namedMock, the "alias" part isn't required. So the code I posted will be generating some code that looks like 

``` php
class MyClassName extends SomeConstantStub
{
    /* Bunch of mockery code that allows you to set up expectations etc */
}

```

This works for me and should probably work for your test case.

``` php
$mock = Mockery::namedMock('MyClassName', 'ClassConstantStub');

$mock->shouldReceive("foo")->andReturn("bar");

var_dump(MyClassName::foo()); // string("bar")                       
```

**Comment by iainfogg** [comment]
Really sorry @davedevelopment - I missed the namedMock (that was a new one on me), sorry for wasting your time there! I'd taken all the other code but not that bit :(

Anyhow, thanks so much for helping me to get this working, really appreciate it!

**Comment by davedevelopment** [comment]
No problem, glad it worked out.

**Comment by peixinchen** [comment]
@davedevelopment - In my scenario, it doesn't work well as expectation. Did I miss something important or I made a mistake?

https://gist.github.com/peixinchen/fa42a98ac6a1897fbd6e8115cde2c2a5

**Comment by davedevelopment** [comment]
@peixinchen not sure about that one, could you perhaps mock up something more complete?

**Comment by sameernyaupane** [comment]
This stub with constant isn't working for me. Is this feature still there? I get no errors but the constant isnt found . ```Fatal error: Undefined class constant```
