### ISSUE TITLE
How to see all calls of an expectation?

### ISSUE THREAD

**Issue by aik099** [padraic/mockery#493]
I've created expectation like this: `$session->shouldReceive('stop')->times(4);` and over time I started to get exception, that method `stop` is being called 6 times instead of 4 times with no exact call points listed.

Is there a way, even by placing breakpoint somewhere inside Mockery code, to see traces of call places to mocked method?

Maybe showing method, that called mocked method in that exception message would also be useful.

**Comment by davedevelopment** [comment]
There's nothing out of the box that I'm aware of and that behaviour is probably incorrect, it should really throw immediately on the 5th attempt.

**Comment by aik099** [comment]
> it should really throw immediately on the 5th attempt.

Then the stack trace in PHPUnit would clearly show who was calling the method for 5th time.

Right now it seems, that expectation count is only validated when `Mockery::close()` is called from `tearDown` method of PHPUnit which is too late to know the context.

Maybe you can point me out in some code inside mockery that it recording each expectation usage so that I can put my breakpoint in there and trace calls this way?

**Comment by davedevelopment** [comment]
@aik099 dropping some code in https://github.com/padraic/mockery/blob/master/library/Mockery/Mock.php#L704 should sort you out.

**Comment by aik099** [comment]
Thanks, will try that shortly.
