### ISSUE TITLE
Blank should receive

### ISSUE THREAD

**Issue by bweston92** [padraic/mockery#494]
My test had `$mock->shouldReceive()->once()` instead of `$mock->shouldReceive('method')->once()` which because my with was quite large I didn't notice. Maybe we should throw an exception if no method name is passed?

![image](https://cloud.githubusercontent.com/assets/1764057/9008282/0d857f7a-3791-11e5-833e-8d25cfb16089.png)

Recommended by @davedevelopment

**Comment by Caroga** [comment]
+1

**Comment by davedevelopment** [comment]
A fix there, but in retrospect, we do have an argument in the signature, so you should check your PHP error_reporting settings as you should have received a missing argument warning from the engine

**Comment by bweston92** [comment]
Ok that was a recent change which isn't in any tagged release. https://github.com/padraic/mockery/commit/520d08ca80ae8e7e5d554c984b8ba5a0b9c35d94

**Comment by davedevelopment** [comment]
Ah I see, cool.
