### ISSUE TITLE
Mocking PDO creates Mockery files in /tmp containing class PDOStatement {}

### ISSUE THREAD

**Issue by anlutro** [padraic/mockery#502]
Reduced to the smallest possible example code:

```php
<?php
require 'vendor/autoload.php';
$pdo = Mockery::mock('PDO');
$pdo->shouldReceive('prepare')->once()->with(null)
	->andReturn($stmt = Mockery::mock('PDOStatemement'));
```

This writes a file with a random name prefixed with "Mockery" to /tmp and it's never removed. The file contains the following:

```php
<?php class PDOStatement {}
```

Mockery version: 0.9.4
PHP version: 5.6.11

**Comment by davedevelopment** [comment]
Check the spelling of `PDOStatemement`?

**Comment by anlutro** [comment]
I realize it's typoed, I probably should have changed the names to "ClassOne" to make it more clear.

Is it still intentional that /tmp gets bogged down with Mockery-files if the class being mocked doesn't exist?

**Comment by anlutro** [comment]
Just doing `Mockery::mock('ClassThatDoesNotExist')` causes the file to be written. I thought this wasn't the case earlier but guess I was mistaken.

**Comment by davedevelopment** [comment]
Ah ok, yeah I believe it's a necessary evil to create the file and include rather than eval it, but I think since #488 we should be tidying those up now.

**Comment by anlutro** [comment]
Aha. Yeah, I just tested with dev-master and there are no files in /tmp. Thanks for your time!
