### ISSUE TITLE
NoMatchingExpectationException removes spaces, causes frustration.

### ISSUE THREAD

**Issue by RobQuistNL** [padraic/mockery#503]
A lot.

I've spent some time figuring out why this code didn't work;

```
$this->mockedObject->shouldReceive('push')->with('foobar');
```

```
1) Test\MyTest
Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_7_Test::push("foobar"). Either the method was unexpected or its arguments matched no expected argument list for this method
```

HOWEVER it turned out that my code was not sending "foobar" but "foo bar" and the spaces were stripped from the output. 

```
$this->queue->shouldReceive('push')->with('foo bar');
```

```
OK (1 test, 3 assertions)
```

I understand where this might come from (because huge dumps are hard to read) but this is very frustrating. 

I would suggest not stripping spaces - or any whitespace at all, to prevent this kind of stuff.

**Comment by davedevelopment** [comment]
Hmmm, I can see why that would be annoying! 

What version are you using? I just tried a quick test and couldn't replicate it in master:

``` php
<?php

require "vendor/autoload.php";

$mock = Mockery::mock();
$mock->shouldReceive('push')->with('foobar');

$mock->push('foo bar');

# PHP Fatal error:  Uncaught exception
# 'Mockery\Exception\NoMatchingExpectationException' with message 'No matching
# handler found for Mockery_0::push("foo bar"). Either the method was unexpected
# or its arguments matched no expected argument list for this method            
```

**Comment by RobQuistNL** [comment]
Got it - the issue is when passed variables are in arrays. See this example;

```php
<?php

require "vendor/autoload.php";

$mock = Mockery::mock();
$mock->shouldReceive('push')->with(['foobar', 'var 2']);

$mock->push('foo bar', 'argument 2', ['var' => 'Array value 2']);

# PHP Fatal error:  Uncaught exception 
# 'Mockery\Exception\NoMatchingExpectationException' with message 
# 'No matching handler found for Mockery_0::push("foo bar", "argument 2", array('var'=>'Arrayvalue2',)).
# Either the method was unexpected or its arguments matched no expected argument list for this method

**Comment by RobQuistNL** [comment]
I think there's some whitespace / newline trimming regex cast on var_export's somewhere..

**Comment by RobQuistNL** [comment]
Another fun fact - booleans in arrays are displayed as string (true => 'true') in those exceptions.

**Comment by davedevelopment** [comment]
@RobQuistNL please review #504 if you get a moment

**Comment by RobQuistNL** [comment]
Tested the case, and that PR solves a lot of issues! Markup is better, no more oldskool array() notation, bools are fixed and the spaces as well. :+1: for you, great work!
