### ISSUE TITLE
Return type for self is not mocked correctly

### ISSUE THREAD

**Issue by Majkl578** [padraic/mockery#511]
Mockery fails to mock `self` return type properly. The following code results in a fatal error:

```php
class Test {
	function foo() : self {}
}

Mockery::mock(Test::class);
```

`Fatal error: Declaration of Mockery_0_Test::foo(): Mockery_0_Test must be compatible with Test::foo(): Test`

**Comment by slax0rr** [comment]
Is there any update or workaround for this bug?
