### ISSUE TITLE
Fatal error is triggered when error or exception occurs during instantiation using unserialisation

### ISSUE THREAD

**Issue by rjkip** [padraic/mockery#512]
A fatal error is triggered when an exception occurs during instantiation using unserialisation:

> PHP Fatal error:  Cannot use Exception as Exception because the name is already in use

Runtime:	PHP 5.6.14-1+deb.sury.org~trusty+1 with Xdebug 2.3.2

The cause of this error is that `\Exception` is imported as `Exception` in `\Mockery\Instantiator`, while a class name `Exception` already exists in that namespace (`\Mockery\Exception`). The solution appears to be to apply the below patch:

```diff
diff --git a/library/Mockery/Instantiator.php b/library/Mockery/Instantiator.php
index 9006496..f396fd8 100644
--- a/library/Mockery/Instantiator.php
+++ b/library/Mockery/Instantiator.php
@@ -20,7 +20,6 @@
 namespace Mockery;
 
 use Closure;
-use Exception;
 use ReflectionClass;
 use UnexpectedValueException;
 use InvalidArgumentException;
@@ -135,7 +134,7 @@ final class Instantiator
 
         try {
             unserialize($serializedString);
-        } catch (Exception $exception) {
+        } catch (\Exception $exception) {
             restore_error_handler();
 
             throw new UnexpectedValueException("An exception was raised while trying to instantiate an instance of \"{$reflectionClass->getName()}\" via un-serialization", 0, $exception);

```

A fully qualified reference to `\Exception` is already used five lines above the catch clause.

Would you like me to open a PR with this patch? I can provide a regression test if so required.

**Comment by davedevelopment** [comment]
PR would be very welcome, thanks!

**Comment by przepompownia** [comment]
New release is needed for installation by composer. 0.9.5 is currently installed by default and still contains this error.

**Comment by bencromwell** [comment]
Just ran into this issue - is there a release pending?

**Comment by davedevelopment** [comment]
@bencromwell here you go https://github.com/padraic/mockery/releases/tag/0.9.6

**Comment by bencromwell** [comment]
Cheers @davedevelopment !
