### ISSUE TITLE
Enable checking of existence of mocked method

### ISSUE THREAD

**Issue by janedbal** [padraic/mockery#516]
Is there any way that I can tell mockery to check that I'm trying to mock method that doesn't exist on original class? I understand it cannot be default behaviour, but it would be very nice to be possible to enable that warning.

```php
class User {
    public function getUsername(){}
}

$user = Mockery::mock(User::class);
$user->shouldReceive('getName'); // I would love to be warned when trying to do this

$user->getName(); // for example I renamed the method and missed this occurence 
```

**Comment by davedevelopment** [comment]
``` php
\Mockery\Configuration::allowMockingNonExistentMethods(false);
```

**Comment by janedbal** [comment]
Thank you, that is what I was looking for...

**Comment by JasonTheAdams** [comment]
@davedevelopment Does this sort of thing still exist? I tried to use the static method you described but it doesn't seem to exist anymore.

**Comment by JasonTheAdams** [comment]
Never mind, I found the new way to do this:
```php
Mockery::getConfiguration()->allowMockingNonExistentMethods(false);
```
