### ISSUE TITLE
PHP7 Scalar Parameters and Return Types Fail to Mock

### ISSUE THREAD

**Issue by jakezatecky** [padraic/mockery#523]
When upgrading a project to PHP 7, I noticed that Mockery seemed to not play nicely with the newer scalar parameters and return types PHP 7 offers.

In particular, I noticed that Mockery did not seem to mock objects properly if there was a method using the scalar type `int`. Interestingly, type `integer` works without issue. Further, I noticed that simple return types appeared to not be properly mocked either. See below the simple PHP7 class, a simple mocking of the class, and the returned output:

``` php
<?php
namespace Something;

class SomeClass
{
	public function scalarParameters(int $one, string $two)
	{
		//
	}

	public function returnTypeHint(): string
	{
		return 'string';
	}
}
```
``` php
<?php

use Mockery as m;
use Something\SomeClass;

class SomeClassTest extends \PHPUnit_Framework_TestCase
{
	public function testSimpleMock()
	{
		$mock = m::mock('Something\SomeClass');
	}
}
```

```
Warning: Uncaught Declaration of Mockery_0_Something_SomeClass::scalarParameters(integer $one, string $two) should be compatible with Something\SomeClass::scalarParameters(int $one, string $two)

D:\wamp\www\mockery-test\vendor\mockery\mockery\library\Mockery\Loader\EvalLoader.php:16
D:\wamp\www\mockery-test\vendor\mockery\mockery\library\Mockery\Container.php:219
D:\wamp\www\mockery-test\vendor\mockery\mockery\library\Mockery.php:74
D:\wamp\www\mockery-test\tests\Something\SomeClassTest.php:10

  thrown in D:\wamp\www\mockery-test\vendor\mockery\mockery\library\Mockery\Loader\EvalLoader.php(16) : eval()'d code on line 25

Fatal error: Declaration of Mockery_0_Something_SomeClass::returnTypeHint() must be compatible with Something\SomeClass::returnTypeHint(): string in D:\wamp\www\mockery-test\vendor\mockery\mockery\library\Mockery\Loader\EvalLoader.php(16) : eval()'d code on line 25
```

From the output above, I found out that the `integer` type hint would fix the Mockery error. However, `int` is a perfectly valid PHP7 type hint, so this should not be causing problems. The error above also seems to indicate that the mocked object is not properly capturing the return type declaration.

**Comment by jakezatecky** [comment]
Return type issues a duplicate of #511.

**Comment by etcinit** [comment]
Having the same issue with PHP 7. Oddly enough, it does work on the HHVM nightly with `hhvm.php7.all = 1`.

**Comment by davedevelopment** [comment]
What version of mockery are you using? Against the master branch and PHP 7.0.0RC1 (I haven't compiled the release yet), I get:

```
<?php

use Mockery as m;

require "vendor/autoload.php";

class SomeClass
{
    public function scalarParameters(int $one, string $two)
    {
        //
    }

    public function returnTypeHint(): string
    {
        return 'string';
    }
}

$mock = Mockery::spy(SomeClass::class);
var_dump($mock instanceof SomeClass); // bool(true)
var_dump($mock->returnTypeHint()); // string("")           
```

Which appears correct to me?

**Comment by paulredmond** [comment]
I can confirm as @davedevelopment suggests that using master should fix your issue.

I just upgraded one of my apps (~ 200 tests) and started seeing failures after adding type and return declarations. I was able to get tests passing again with the following which works for me for now until a stable release is available:

```json
"require-dev": {
  "mockery/mockery": "dev-master"
}
```

**Comment by jakezatecky** [comment]
@davedevelopment 's suggestion of using the master branch works.
