### ISSUE TITLE
Mocking interfaces with allowMockingNonExistentMethods(false).

### ISSUE THREAD

**Issue by SamMousa** [padraic/mockery#529]
Not very familiar with Mockery yet, this could be desired behavior.

1. I have an interface `Test` with one function. 
````
interface Test {
    public function test();
}
````
2. I disable mocking non existing methods:
````
\Mockery::getConfiguration()->allowMockingNonExistentMethods(false);
````
3. I create a mock of that interface.
````
$mock = \Mockery::mock('Test')
````
4. I add an invalid expectation
````
$mock->shouldReceive('coolStuff')->andReturn(5);
````
5. I call the mocked method.
````
echo $mock->coolStuff();
: 5
````

Since the mocked interface is anonymous, snippet belows shows the code:
````
public function mockery_isAnonymous()
    {
        $rfc = new \ReflectionClass($this);
        return false === $rfc->getParentClass();
    }
````

And the guard in `Mockery::buildDemeterChain()` requires it to not be anonymous:
````
 if (!\Mockery::getConfiguration()->mockingNonExistentMethodsAllowed()
            && !$mock->mockery_isAnonymous()
            && !in_array(current($methodNames), $mock->mockery_getMockableMethods())
````

I am allowed to mock methods regardless of them being in the interface.

Should this be allowed?

**Comment by SamMousa** [comment]
A workaround to prevent this is mocking both `stdClass` and the desired interface(s):
````
$mock = \Mockery::mock('stdClass', 'Test');
````

When done like this the mocked class is no longer anonymous and the configuration setting will work as expected.

**Comment by davedevelopment** [comment]
I do believe this is a bug

**Comment by SamMousa** [comment]
A fix would be to create an empty base class (or use `stdClass`) if only interfaces are specified, want me to create a PR?

**Comment by davedevelopment** [comment]
I think changing `mockery_isAnonymous` might be better? I.e. if the class implemented any more interfaces than just `Mockery\MockInterface`, it would not be anonymous.

**Comment by SamMousa** [comment]
ok sounds good, pr incoming

**Comment by SamMousa** [comment]
Thanks, sry for forgetting this! @TiagoMaiaL thanks!
