### ISSUE TITLE
Mocking object function arguments using ->with() do not behave as expected.

### ISSUE THREAD

**Issue by kwhat** [padraic/mockery#536]
I noticed that I cannot do the following to check that an object with the correct properties is passed to my mock object.

```
$mockArg = new stdClass();

Mockery::mock("My\Awesome\Object")
    ->shouldReceive("awesome")
    ->with($mockArg)
   ->once();
```

Instead I need to work around the issue with something like this.

```
$mockArg = new stdClass();

Mockery::mock("My\Awesome\Object")
    ->shouldReceive("awesome")
    ->with(Mockery::on(function($arg) use ($mockArg) {
        return $arg == $mockArg;
    }))
   ->once();
```

Php states comparing objects using '==' and/or '===' is the preferred practice (See: http://php.net/manual/en/language.oop5.object-comparison.php), so why does Mockery not support this type of comparison?  It seems fairly trivial to implement, I just want to make sure that there isn't a reason that I don't know about for this oversight.

Proposed Solution:

```
--- vendor/mockery/mockery/library/Mockery/Expectation.php  2016-01-21 16:42:29.000000000 -0800
+++ vendor/mockery/mockery/library/Mockery/Expectation.new.php  2016-01-21 16:41:47.000000000 -0800
@@ -327,6 +327,12 @@
                 return true;
             }
         }
+        if (is_object($expected) && is_object($actual)) {
+            $result = $actual == $expected;
+            if ($result) {
+                return true;
+            }
+        }
         if ($expected instanceof \Mockery\Matcher\MatcherAbstract) {
             return $expected->match($actual);
         }
```

**Comment by davedevelopment** [comment]
This has come up a few times and is something we need to make a decision on. I don't like the current behaviour, but it's quite a big break in terms of backwards compatibility.

Previously raised here #328
It's mentioned in the issue we have for moving towards 1.0 #288

**Comment by kwhat** [comment]
Seems like your solution [here](https://github.com/padraic/mockery/issues/328#issuecomment-41898736) would be a good fit for 1.0.  Feel free to close this bug and attached PR after you figure out what you want to do for #288.

Thanks.

**Comment by davedevelopment** [comment]
Closing this one, I'm going to maintain BC for now. I'm proposing to deprecate the MustBe matcher in #689.
