### ISSUE TITLE
Bump version to 0.9.5

### ISSUE THREAD

**Issue by kwn** [padraic/mockery#538]
Hi @davedevelopment

How about bumping a version to 0.9.5? Last release was over 9 months ago. I had a quick look at commits list, and it doesn't seem that BC has been broken (I would appreciate if you could double check this). It's quite important I think, since some bugs related to PHP7 has been fixed, and obviously PHP7 is getting more popular.

I would appreciate if you could consider this request and create a new tag.

**Comment by GrahamCampbell** [comment]
The next version will be 1.0.0 since there are breaking changes since 0.9.4.

**Comment by kwn** [comment]
@GrahamCampbell 
Cool, nice to hear that. Do you know any time window for 1.0.0 release?

**Comment by GrahamCampbell** [comment]
I think it might be a while yet. There's still a fair bit to do.

**Comment by davedevelopment** [comment]
Yeah, I think you'd be best hooking up to dev-master or a single commit for now.

**Comment by kwn** [comment]
Ok, thanks guys.
