### ISSUE TITLE
andThrows with custom parameters

### ISSUE THREAD

**Issue by danhanly** [padraic/mockery#539]
I have an exception that extends another, and assembles a message based upon, passing it to the parent constructor:

```php
class CustomException extends Exception
{
    public function __construct(array $response)
    {
        $message = "";
        foreach($response as $error) {
            $message = "Error: $error\n";
        }
        parent::__construct($message);
    }
}
```

This type of setup isn't able to be triggered via Mockery since the `andThrow` method forces a string message, not any other method.

Is there a way around this?

**What I've tried**

```php
$mock->andThrow(new CustomException(['test', 'test2']));
$mock->andThrow(CustomException::class, ['test', 'test2]);
```

**Comment by davedevelopment** [comment]
Maybe you could new up the exception manually? I think that works.

``` php
$mock->shouldReceive("foo")->andThrow(new CustomException(['some error']));
```

**Comment by danhanly** [comment]
Doesn't the `andThrow` method only accept a string as reference to the exception to be thrown?

I'll give it a spin.

**Comment by danhanly** [comment]
This worked. Thanks
