### ISSUE TITLE
"hamcrest/hamcrest-php": "^2.0@dev" dependency, composer fails

### ISSUE THREAD

**Issue by ddimaria** [padraic/mockery#541]
Hi, composer is now failing when updating mockery (see below).  I can't find a 2.0 branch on the hamcrest/hamcrest-php package, so guessing that this needs to be 1.2?  Thanks!

- mockery/mockery dev-master requires hamcrest/hamcrest-php ^2.0@dev -> no matching package found.
- mockery/mockery dev-master requires hamcrest/hamcrest-php ^2.0@dev -> no matching package found.
- Installation request for mockery/mockery dev-master -> satisfiable by mockery/mockery[dev-master].

**Comment by GrahamCampbell** [comment]
Not a bug.

**Comment by chrismou** [comment]
@ddimaria Is it the same issue as mentioned here: https://github.com/padraic/mockery/pull/535#issuecomment-175566525 ?  Might need to change your minimum-stability, or manually include hamcrest

**Comment by aik099** [comment]
This would be automatically when Hamcrest 2.0 would be release. @davedevelopment , are you planning to release soon?

**Comment by davedevelopment** [comment]
@aik099 I don't know, I thought I'd give it a little time to see if there was anything else we wanted to break BC wise, rather than rush in to it and have to break again.

**Comment by aik099** [comment]
OK. I'm wondering what Mockery version people are using, that requires them to use Hamcrest 2.0, that is not released. Probably a `dev-master`. Maybe the README/documentation still says use `dev-master`.

I've checked that `0.9.4` (latest released version) depends on Hamcrest ~1.1.

**Comment by GrahamCampbell** [comment]
If you're using a dev version of mockery, I don't think it's unreasonable for us to have non-stable dependencies...

**Comment by aik099** [comment]
Using `dev-master` version of Mockery usually isn't that much of a problem, because the `@dev` stability flag from Mockery's `composer.json` is ignored and attempt to use stable Hamcrest 2.0 release in made.

It's just that in this particular case we haven't released Hamcrest 2.0 and that in turn creates problems.

**Comment by GrahamCampbell** [comment]
> because the @dev stability flag from Mockery's composer.json is ignored and attempt to use stable Hamcrest 2.0 release in made.

Yes, indeed. What I'm saying is that we shouldn't need to care about this. People using dev mockery should work this out and set appropriate minimum stability.

**Comment by aik099** [comment]
OK.

**Comment by meglio** [comment]
For those who's wondering "SO, what is the workaround":

```json
"require-dev": {
    "hamcrest/hamcrest-php": "@dev"
  },
```

This allows hamcrest versions with stability = `dev` to be loaded into your project.

**Comment by GrahamCampbell** [comment]
No, that's not the work around. That would result in a wildcard dependency.

**Comment by Rezouce** [comment]
There is a bug in the current stable versions for which the solution given is to use the dev-master branch:
https://github.com/padraic/mockery/issues/523

Is there any plan for having a working dev-master branch or a new tag version in the near future?

**Comment by davedevelopment** [comment]
The dev-master branch works just fine, require a dev version of hamcrest manually or add this to your composer.json

```
    "minimum-stability": "dev",
    "prefer-stable": true
```

**Comment by Rezouce** [comment]
It worked, thanks.

**Comment by Giuseppe-Mazzapica** [comment]
Since a non-dependency like Hamcrest has been added as a dependency, more has been the problems than the benefits.

I'm still hard-requiring v0.9.3 everywhere because of that...

**Comment by davedevelopment** [comment]
I just tagged 2.0.0 of hamcrest php, should make it a bit easier.
