### ISSUE TITLE
PHP 7 : unable to mock return types

### ISSUE THREAD

**Issue by ctrlaltdylan** [padraic/mockery#547]
Have tested with both `bool` and object return types, Mockery does not define a return type on an object mock. When the mock is passed as an argument, the declared return type complains:

```
class Stub {
     public function returnType() : bool
     {
           return true;
     }
}

class TestingCode {
    public function example(Stub $stub) : bool
    {
        return $stub->returnType();
    }
}

// test
public function testTestingCodeReturnType()
{
    $stub = Mockery::mock(Stub::class);
    $testing = new TestingCode();
    $this->assertTrue($testing->example($stub));
}
```

`PHP Fatal error:  Declaration of TestingCode::example(Stub $stub) must be compatible with TestingCode::example(Stub $stub) : bool`

**Comment by davedevelopment** [comment]
Have you tried this against the master branch?

**Comment by ctrlaltdylan** [comment]
Every time I make a silly mistake like this I realize I just need to drink more coffee.
