### ISSUE TITLE
wrong requirements for mockery 0.9.4

### ISSUE THREAD

**Issue by rjsandim** [padraic/mockery#552]
In Packgist (https://packagist.org/packages/mockery/mockery) mockery 0.9.4 has 5.3.2 as minimum requirement and because of file https://github.com/padraic/mockery/blob/master/tests/Mockery/MockingVariadicArgumentsTest.php on line 51 has a feature of php 5.6. Am I right?

I'm not getting 0.9.4 because of it and my project is php 5.5.26.

**Comment by aik099** [comment]
But that test you've mentioned might be included conditionally, when tests are executed on PHP 5.6+ version Travis CI as well.

**Comment by aik099** [comment]
Looking at `composer.json` you should get `0.9.4` after doing `composer update` on any PHP version above 5.3.2.

**Comment by rjsandim** [comment]
Thank you, It was a miss setup on my PhpStorm. It was running mockery tests over php 5.5.26 (I don't know why hhahaha) and it was throwing error about the file that I've commented.
