### ISSUE TITLE
Fatal error when trying to use Mockery::namedMock() in a class with an abstract method

### ISSUE THREAD

**Issue by TiagoMaiaL** [padraic/mockery#557]
Guys, when trying to reproduce the issue [525](https://github.com/padraic/mockery/issues/525), I found another little bug. NamedMock isn't capable of generating a method with the same parameter declarations as the specified superclass. It gives a fatal error:

Illustration and reproducible steps (Those are based on the ones within issue 525):

I've created a small file to contain dummy namespaces and classes definitions:
```PHP
namespace Nature
{
    class Plant
    {
    }
}

namespace
{
    abstract class Gardener
    {
        abstract public function water(Nature\Plant $plant);
    }
}
```

In a new test method inside NamedMockTest:

```PHP
// require the dummy test classes.
// ...
$cactus = new \Nature\Plant();
$gardener = Mockery::namedMock(
    "NewNamespace\\ClassName",
    Gardener::class,
    array('water' => true)
);
$this->assertTrue($gardener->water($cactus));
```

The result of the previous test invocation is expressed in the following screenshot:
![screen shot 2016-03-02 at 12 00 52 pm](https://cloud.githubusercontent.com/assets/6910889/13464186/ac5eb81a-e06e-11e5-8a3f-e5941fa5af2a.png)

**Comment by Sazpaimon** [comment]
Any chance of this getting merged? I just ran into this myself.
