### ISSUE TITLE
Mock multiple method call with return and throw

### ISSUE THREAD

**Issue by iro88** [padraic/mockery#562]
I cant mock method that once throw exception and next run return normal value.

**Comment by TiagoMaiaL** [comment]
Could you illustrate your problem with the code you're trying to get working? It's better for the people to replicate the problem.

**Comment by davedevelopment** [comment]
I'd do that this way:

``` php
$mock = Mockery::mock();
$mock->shouldReceive("foo")->andReturnUsing(function () {
    static $counter = 0;

    if (++$counter == 1) {
        throw new Exception("It's a trap");
    }

    return 123;
});
