### ISSUE TITLE
Outdated copyright information

### ISSUE THREAD

**Issue by TiagoMaiaL** [padraic/mockery#569]
All the file headers are presenting 2010-2014 at the copyright docblocks, should the headers be presenting 2010-2016 instead? Also, should all the files contain the project's header? I know these are not substantial issues, but these issues can also be easily fixed by a pull request.

**Comment by davedevelopment** [comment]
Regarding the copyright years, I think just keeping the year of publication is suitable, then we don't need to update it all the time.

Don't know about the project's header! I never bother putting them in, just seem like wasted bytes to me, the licence is in the root of the repo and is good enough for me.

**Comment by TiagoMaiaL** [comment]
I understand. Do you think it'd be ok if all the other headers(except the one at the root) were erased from the files?

**Comment by davedevelopment** [comment]
I think go with the header for now! @padraic put them in, so better to have them in, so go wild and get them in everywhere :)

**Comment by TiagoMaiaL** [comment]
Nice, this is a pull request I'm going to make.
