### ISSUE TITLE
Full mock of exception with no expectations work

### ISSUE THREAD

**Issue by zodiac** [padraic/mockery#581]
I am trying to track down differences in mockery behavior under zend and hhvm and ran into what I think is a bug when full-mocking `Exception`.

```
<?php

include('./vendor/autoload.php');

class K {
  function getMessage() {
    return 'hi';
  }
}

$r1 = Mockery::Mock('K');
var_dump($r1->getMessage());

$r2 = Mockery::Mock('K')->makePartial();
var_dump($r2->getMessage());

$r3 = Mockery::Mock('Exception');
var_dump($r3->getMessage());

$r4 = Mockery::Mock('Exception')->makePartial();
var_dump($r4->getMessage());
```

In the code above, both partial mocks (`r2` and `r4`) should defer the call of `getMessage` to the class being mocked, and this is what happens in both zend and hhvm.

Also, in both engines, when calling `getMessage` on a non-partial mock of `K` (ie on `r1`), a `BadMethodCallException` is thrown, since no expectations were set on `r1`.

This leads me to believe that a `BadMethodCallException` should also be thrown on `r3`. This is what mockery does on hhvm, but on zend, the an empty string is returned. Is this expected behavior?

**Comment by davedevelopment** [comment]
Zend's implementation has `getMessage` (and most of the other methods on `Exception`) as `final`, so we can't generate code to intercept the call, I guess HHVM doesn't mark them as `final`.

**Comment by 4n70w4** [comment]
So how can I make a mock exception getMessage()? I also can't get wet Throwable:

```
PHP Fatal error:  Class Mockery_4_Throwable cannot implement interface Throwable, extend Exception or Error instead in /var/www/html/vendor/mockery/mockery/library/Mockery/Loader/EvalLoader.php(34) : eval()'d code on line 30
```
