### ISSUE TITLE
Cannot use "int" scalar typehint, must use "integer"

### ISSUE THREAD

**Issue by tpavlek** [padraic/mockery#583]
If I have a class with a scalar typehint:

```
public function myFunc(int $id);
```

if I try to mock that class, Mockery will throw the error that the mocked class method declaration is incompatible because Mockery attempts to declare the signature as

```
public function myFunc(integer $id);
```

Simply changing the original function to use `integer` instead of shorthand `int` is a sufficient workaround for now.

**Comment by GrahamCampbell** [comment]
Seems odd. `int` is the preferred version, with `integer` the alias.

**Comment by davedevelopment** [comment]
Did you try against `master`?

``` php
<?php

declare(strict_types=1);

require "vendor/autoload.php";

class Foo {
    public function myFunc(int $id) { }
}

$mock = Mockery::mock(Foo::class);
$mock->shouldReceive("myFunc")->andReturn(123);
var_dump($mock->myFunc(456)); // int(123)        


```

**Comment by tpavlek** [comment]
Just tried against `master` - correct, it works. The 0.9.4 release still has this bug, so next release should fix it.

Thanks!
