### ISSUE TITLE
Documentation mismatch, "andReturnUsing" does not work?

### ISSUE THREAD

**Issue by piotrkochan** [padraic/mockery#590]
Mocked method `$redis->scan()` always returns `NULL`. If I use something else than `andReturnUsing($callback)` it works well (`eg. andReturn(123)`).

Weird thing is that `andReturnUsing($callback)` works well with mocked '\Redis' but no '\MyNapespace\Redis' or '\MyNapespace\Redis[scan]'

```
$closure = $closure = function (&$iterator, $pattern = '', $count = 5) { return array... }
$redis = \Mockery::mock('\MyNapespace\Redis[scan]')
            ->shouldReceive('scan')
            ->atMost()->times($result_sets)
            ->andReturnUsing($closure)
            ->getMock();
```

**Comment by piotrkochan** [comment]
According to http://docs.mockery.io/en/latest/reference/argument_validation.html
`$this->mock->shouldReceive('foo')->withArgs($closure);`

Does not work also, withArgs accepts arrays only.

I've found some example with argument reference:
http://jontai.me/blog/2012/04/flexible-mock-objects-with-mockery/

```
class Model
{
    function setLastModified(&$data)
    {
        $data['lastModified'] = date('c');
        return $this;
    }
}

$mock = \Mockery::mock('Model');
$mock->shouldReceive('setLastModified')
     ->with(\Mockery::on(function(&$data) {
         $data['lastModified'] = '2012-02-12T15:19:21+00:00';
         return true; // indicate expectation matched
     }));
 
$values = array('foo' => 'bar');
$mock->setLastModified($values);
echo $values['lastModified']; // prints '2012-02-12T15:19:21+00:00'
```

But `Mockery::on(function(&$data) {` does not affect a `$values` array. It is still the same as before.

I'm going to try mockery 0.9.3 against 0.9.4

**Comment by davedevelopment** [comment]
I think it's probably something to do with `$closure` expecting a reference.

```
$this->mock->shouldReceive('foo')->withArgs($closure);
```

Will only work in master.

**Comment by piotrkochan** [comment]
So should I use master branch? I prefer release much more

**Comment by piotrkochan** [comment]
Now I see that composer installed 0.9.3 so now I'm updating to 0.9.4

**Comment by davedevelopment** [comment]
I'd just use master.
