### ISSUE TITLE
Add Interface For DefinedTargetClass and UndefinedTargetClass.

### ISSUE THREAD

**Issue by TiagoMaiaL** [padraic/mockery#591]
What do you guys think about adding an interface for these two classes? They're pretty similar. This approach would increase code security, since we can expect and predict a common interface dictated in a contract pattern. The only difference between the two interfaces is the implementation of `__toString()` and `getInterfaces()` in the `DefinedTargetClass`.

**Comment by davedevelopment** [comment]
Sure!
