### ISSUE TITLE
Mocking demeter chain method erases class type

### ISSUE THREAD

**Issue by aarantes-engage** [padraic/mockery#594]
I'm trying to mock a `Car` object with a demeter chain for honking the horn (eg. `$car->horn()->honk()`). 

For some reason `$mockCar instanceof Car` yields `true` for

`$mockCar = Mockery::mock(Car::class)->shouldRequire('horn')->mock();`

but `false` for

`$mockCar = Mockery::mock(Car::class)->shouldRequire('horn->honk')->mock();`

This makes it difficult to pass mock objects to functions such as `function driveCar(Car $car) {...}`

It seems to me that the methods that are mocked on an object should not affect the type of the object itself. If I add a method bar() to class Foo, that should not change its type from Foo to NotFoo. 

The functionality works correctly when the horn() method is mocked separately to return an instance of Horn instead of using demeter chains in shouldRequire().

Some sample code from a test suite illustrates the problem:

	<?php namespace Unit\Automotive;

	class Car {
		/* ... */
	}

	function driveCar(Car $car) {
	    /*
	       ...
	       $car->horn->honk();
	       ...
	    */
	}

	class AutotiveTest extends TestCase
	{

		public function testCar() {

			// define mock objects
			$mockCar = Mockery::mock(Car::class)
				->shouldReceive('horn')
				->mock();

			$badMockCar = Mockery::mock(Car::class)
				->shouldReceive('horn->honk')
				->mock();

			// debug information
			printf("mockCar is car: %s, get_class()=%s\n",
				$mockCar instanceof Car ? 'true' : 'false',
				get_class($mockCar));

			printf("badMockCar is car: %s get_class()=%s\n",
				$badMockCar instanceof Car ? 'true' : 'false',
			    get_class($badMockCar));

			// this is ok, $mockCar is a Car
			driveCar($mockCar);

			// this throws an exception because $badMockCar is not a Car
			driveCar($badMockCar);

		}
	}

This outputs:

	mockCar is car: true, get_class()=Mockery_0_Unit_Automotive_Car
	badMockCar is car: false get_class()=Mockery_1__demeter_horn

	There was 1 error:

	1) Unit\Automotive\AutotiveTest::testCar
	ErrorException: Argument 1 passed to Unit\Automotive\driveCar() must be an instance of Unit\Automotive\Car, instance of Mockery_1__demeter_horn given, called in /var/www/*redacted*/tests/Unit/Automotive/AutomotiveTest.php on line 46 and defined

**Comment by davedevelopment** [comment]
I believe when you do `shouldRequire('horn->honk)`, it's almost like a macro for 

```
Mockery::mock(Car::class)->shouldReceive('honk')->andReturn(Mockery::mock()->shouldReceive('honk')->getMock())
```
So your last call to `mock` is being called on the mock that is returned from the `honk` call and I think that is desired behaviour.

I would recommend splitting it in to two statements.

``` php
$mockCar = Mockery::mock(Car::class);
$mockCar->shouldReceive('horn->honk');
```

**Comment by aarantes-engage** [comment]
That makes sense. 

`Mockery::mock(Car::class)` returns an object of type `Car` and 
`Mockery::mock(Car::class)->shouldReceive('horn->honk')` returns an object of type `horn`.

Would it be possible to add a line to the documentation at https://github.com/padraic/mockery/blob/master/docs/reference/demeter_chains.rst to remind people not to chain both expressions together?
