### ISSUE TITLE
Partial mock, with never(), once(), twice()... constraints doesn't work

### ISSUE THREAD

**Issue by mihhac** [padraic/mockery#608]
Hi, I have a case with partial mocking. 

mockery version is 0.9.5 and php 5.6.

Class A {
    protected function foo(){echo 'foo';}
}

Class B extends A {
    public function bar() {$this->foo();}
}

$mock = \Mockery:mock('B[foo]')->shouldAllowMockingProtectedMethods();
$mock->shouldReceive('foo')->never();

$mock->bar();

**Comment by davedevelopment** [comment]
Do you need to do `Mockery::close()`?

**Comment by mihhac** [comment]
Ah, my bad, many thanks! With Mockery::close() works nicely.
