### ISSUE TITLE
Mocking void methods in PHP 7.1

### ISSUE THREAD

**Issue by klapuch** [padraic/mockery#635]
Hi,
during mocking void methods I end up with **Fatal error: A void function must not return a value in /var/www/project/vendor/mockery/mockery/library/Mockery/Loader/EvalLoader.php(34) : eval()'d code on line 825** (This message is from master, but the same error I get from ^0.9.5 version)

eval()'d code:
``` php
public function put(\Vendor\LogLibrary $log): void {
   $argc = func_num_args();
   $argv = func_get_args();
   $ret = $this->_mockery_handleMethodCall(__FUNCTION__, $argv);
   return $ret; // the 825th line
}
```
Is there a possibility how to avoid the problem?

Thanks in advance

**Comment by davedevelopment** [comment]
I think I have this working in #631

**Comment by klapuch** [comment]
@davedevelopment Thanks for merging, I can't wait to try it.

**Comment by davedevelopment** [comment]
No problem!
