### ISSUE TITLE
Mockery mock partial mutates state

### ISSUE THREAD

**Issue by ddelnano** [padraic/mockery#649]
We just had an issue where Mockery partial mocks we introduced into our code base without issue and were incorporated in passing tests.  Then later on down the line we added more tests to a different part of our codebase that utilized the object who was partially mocked and ran into issues where the partial mock was mutating state.  Not sure if this is a bug or intended behavior but from the documentation it is not obvious what is going on behind the scenes.  If it is a bug I would be happy to give more context into our situation.  If its intended then I feel the docs should be more explicit about this.

**Comment by davedevelopment** [comment]
I am not sure to be honest.

Paste some context and we'll see :)

**Comment by ddelnano** [comment]
Sorry once we realized we had an issue we avoided the feature.  Since I can't give anymore context I am closing this.
