### ISSUE TITLE
An interface specifying the magic __clone method cannot be mocked

### ISSUE THREAD

**Issue by Bilge** [padraic/mockery#669]
```php
interface X {
    public function __clone();
}

Mockery::mock(X::class);
```

>Fatal error: Class Mockery_1_X contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (X::__clone) in Mockery\Loader\EvalLoader.php(16) : eval()'d code on line 25

**Comment by davedevelopment** [comment]
This should let you do it.

``` php
<?php // test.php

require "vendor/autoload.php";

interface Test
{
    public function __clone();
}

$config = new Mockery\Generator\MockConfigurationBuilder();
$config->setBlackListedMethods([]);
$config->addTarget(Test::class);
$mock = Mockery::mock($config);
```

**Comment by Bilge** [comment]
Why did you close this? Do you think that's an acceptable API? Surely this
should be supported by the regular mocking methods.

**Comment by davedevelopment** [comment]
Sorry, I should have explained. 

I don't think it should be supported, as I mentioned or IRC, I don't think `__clone` belongs in an interface and therefore doesn't need supporting. I'm not going to break BC for something I don't consider all that relevant.

**Comment by Bilge** [comment]
That doesn't explain anything. Why can't an interface specify an object
must clone its member objects?

**Comment by Bilge** [comment]
Furthermore, how does such an improvement break BC? Nobody could have
successfully mocked such an interface before so what is being broken by
supporting it?

**Comment by davedevelopment** [comment]
> Why can't an interface specify an object must clone its member objects?

Interfaces can specify interfaces, not behaviour?

> Furthermore, how does such an improvement break BC? Nobody could have successfully mocked such an interface before so what is being broken by supporting it?

True, I hadn't considered just putting a fix in for interfaces.

**Comment by Bilge** [comment]
So can we at least agree to reopen this ticket?

You may or may not be correct that an interface should never, under any
circumstances, specify implementations must implement the magic method
 __clone, but if that is a mistake then it should be my mistake to make.
Mockery is just a mocking framework after all; it is beyond its scope to
protect me from my own stupidity.

**Comment by davedevelopment** [comment]
No, I'm not going to reopen the ticket.

I've provided you with a workaround, that is 4 lines of code, that you will have to use this once. I could probably write four lines of code to hack this in to Mockery itself, but then I would have to maintain for as long as I help out here, when it's not really any use to anyone except you right now this minute.

**Comment by Bilge** [comment]
You cannot possibly project how many people it has affected nor will affect in future, nor how many people reject Mockery as unsuitable because word gets around about arbitrary limitations such as this. 

It is four lines of technical debt regarding Mockery internals I have to copy in to my projects, not once, but in every case where I need to need to mock this interface or one like it.

It is technical debt for me because I am relying on undocumented Mockery internals in a pre-1.0 version subject to change. I cannot be expected to know how to maintain this code should it ever stop working nor expect any of my collaborators to know what this code means nor why I suddenly elect to mock in a manner wildly divergent from the norm.

For these reasons I implore you to reconsider adding first-party support.

**Comment by brianmuse** [comment]
Have had a similar issue with an interface method called `list`.

Results in an error: 
> Foo contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Foo::list)

Is there a reason that the blacklist, by default, includes all of these? Seems like there are some valid class method names on there that could be used.

**Comment by davedevelopment** [comment]
@brianmuse I thought list should be removed correctly. We need `list` in there for < php 7, but I thought we had a mechanism to remove it if you were running >= php 7.

**Comment by Bilge** [comment]
@davedevelopment @robertbasic I'd like this issue to be reopened as I keep coming up against this problem. I do not accept the argument that `__clone` should never be specified in an interface. In my library, cloning is necessary to ensure immutability of state and sometimes we also know that object will require deep cloning, and therefore, **must** implement `__clone` to ensure deep cloning is performed.

**Comment by Bilge** [comment]
@davedevelopment Please reopen this. Not only does this preclude mocking an interface, it also precludes mocking the method in general. That is, the real __clone implementation will still exist and probably be invalid since it will attempt to clone fields that do not exist in the mock. The `MockConfigurationBuilder` workaround of course works, but this is not a user-friendly API and is very verbose. A simpler solution should be available, or the restriction simply removed altogether.

**Comment by davedevelopment** [comment]
Hi @Bilge, my feelings are still the same as they were [here](https://github.com/mockery/mockery/issues/669#issuecomment-274037741).

**Comment by Bilge** [comment]
At least you are consistent, even if that means being consistently wrong. May have something to do with why the library is dead. I suppose it is time for me to move on, too.
