### ISSUE TITLE
phpUnit 6.0 support?

### ISSUE THREAD

**Issue by pavarnos** [padraic/mockery#690]
phpUnit 6.0 drops support for \PHPUnit_Framework_TestCase in favour of \PHPUnit\Framework\TestCase. 

Would you accept a PR with Mockery\Adapter\Phpunit6\MockeryTestCase.php etc with phpunit 6 compatible classes?

**Comment by GrahamCampbell** [comment]
> If so, could we get away with a class_alias call?

Probably not a good idea I think.

**Comment by pavarnos** [comment]
yeah, class_alias might cause other problems. I was suggesting making a copy of the Adapter\Phpunit directory into Adapter\Phpunit6 so that old phpunit5 code would keep working but new code could use the namespaced code from v6. Is that a robust approach?

**Comment by davedevelopment** [comment]
I'll take a look at this today. @pavarnos if you want to send a PR with your ideas, we can compare and contrast, go from there.

**Comment by davedevelopment** [comment]
#691 should work?
