### ISSUE TITLE
Use existing __toString methods for argument and Matcher representation

### ISSUE THREAD

**Issue by ccprog** [padraic/mockery#697]
If an error prints the arguments of an expectation, expected or actual, it represents them via the `Mockery::formatArgument()` method. For objects, this will return a simple `object(className)`. This is unneccessarily obscure when the object has a `__toString()` method. The Matcher interface for example requires them.

**Comment by davedevelopment** [comment]
@ccprog thanks for reporting, see #698 for a partial fix.
