### ISSUE TITLE
[Question] How do I mock with a method that returns :self?

### ISSUE THREAD

**Issue by bkuhl** [padraic/mockery#700]
Here's a snippet of source:

```php
    public function play(string $url) : self
    {
        $this->addStep(new Play($url));

        return $this;
    }

    public function hangup() : self
    {
        $this->addStep(new Hangup());

        return $this;
    }
```

When using this class, I'm writing my mocks like:

```php
        $option = Mockery::mock(Option::class);
        $option->shouldReceive('hangup')->once();
        $option->shouldReceive('play')->andReturn(Mockery::self());
```

I've also tried `andReturn($option)` but either way I end up with the error:

```
atal error: Cannot use 'self' as class name as it is reserved in /private/var/folders/m2/y4sdt3ks3_x206vw2gv37pgc0000gp/T/Mockery55S8Oy on line 1
```

**Comment by davedevelopment** [comment]
@bkuhl I think that's a bug! The return type hints are fairly new and I doubt we (I) considered `self` when implementing...

**Comment by davedevelopment** [comment]
@bkuhl or maybe not, which version of mockery are you using? I think you'll want the master branch or the 1.0.0-alpha1 release.

**Comment by bkuhl** [comment]
Bingo!  I was not using the alpha build.  This works great now, thanks!
