### ISSUE TITLE
Cannot use object of type Mockery_0 as array

### ISSUE THREAD

**Issue by Kwadz** [padraic/mockery#701]
I made a very simple example:

```php
<?php

namespace AppBundle\Manager;

use Mockery as m;
use PHPUnit\Framework\TestCase;

class ProductManagerTest extends TestCase
{
    public function testProductManager()
    {
        $config = m::mock(array('reference'=>'abc', 'type'=>'def'));
        $pm = new ProductManager($config);
    }
}
```

Related class:
```php
<?php

namespace AppBundle\Manager;

class ProductManager
{
    public function __construct($config)
    {
        if (isset($config['reference'])) {
            $this->reference = $config['reference'];
        }
    }
}
```

When I execute `testProductManager()`, I get:

`Fatal error: Cannot use object of type Mockery_0 as array`

Am I using a wrong way to mock an array or something else is wrong?

**Comment by davedevelopment** [comment]
You don't really want or need to mock an array, I would recommend just passing an array.

``` php
    public function testProductManager()
    {
        $config = array('reference'=>'abc', 'type'=>'def');
        $pm = new ProductManager($config);
    }
```

**Comment by Kwadz** [comment]
Ok, in which case should we use the following paragraph in the [quick reference ](http://docs.mockery.io/en/latest/reference/startup_methods.html#quick-reference
)?

>`$mock = \Mockery::mock(array('foo'=>1,'bar'=>2));`
>
>Creates a mock object named unknown since we passed no name. However we did pass an expectation array, a quick method of setting up methods to expect with their return values.

**Comment by davedevelopment** [comment]
@Kwadz That would set up an test double, stubbing calls to the `foo` and `bar` methods.

``` php
$mock = \Mockery::mock(array('foo'=>1,'bar'=>2));

$mock->foo(); // int(1)
$mock->bar(); // int(2)
```
