### ISSUE TITLE
Mockery object is calling __set() method on mocked class

### ISSUE THREAD

**Issue by salcode** [padraic/mockery#717]
I'm working with the [Stripe PHP Library](https://github.com/stripe/stripe-php) and creating a mock of  
[\Stripe\Customer](https://github.com/stripe/stripe-php/blob/master/lib/Customer.php), which extends  
[\Stripe\ApiResource](https://github.com/stripe/stripe-php/blob/master/lib/ApiResource.php), which extends  
[\Stripe\StripeObject](https://github.com/stripe/stripe-php/blob/master/lib/StripeObject.php)

When I create my mock with 

```
$customer              = m::mock('\Stripe\Customer');
$customer->id          = 'example_customer_id';  // This works.
$customer->description = 'Description of customer'; // This fails.
```

The error I get is

```
There was 1 error:

1) Mockery_Property_TestCase::test_mockery_property
Error: Call to a member function add() on null

/vendor/stripe/stripe-php/lib/StripeObject.php:105
/tests/test-stripe-customer-property-method.php:12
```

The line referenced in `lib/StripeObject.php` is in the [__set() method](https://github.com/stripe/stripe-php/blob/master/lib/StripeObject.php#L86-L107) for that object.

I've referenced the Mockery documentation and http://docs.mockery.io/en/latest/reference/public_properties.html indicates

> So please mock virtual properties (those relying on __get() and __set()) as if they were actually declared on the class.

but I think that is what I'm doing.  I apologize if I've missed something and would be happy to do further reading if you point me in the best direction.

I did review some of the other issues on this repo, including #108 which discusses the Mockery `set()` method, but that seems to only be applicable after a method has been called.

I've created a minimal reproducible example at https://github.com/salcode/mockery-stripe-property-issue.

Thank you for this project and the work you put into it.

**Comment by davedevelopment** [comment]
Hi @salcode, sorry for the delay in getting back to you and thank you for the detailed report.

I'm not sure what the best behaviour for Mockery is with regards to __set and __get to be honest, but I think for your use case, you can work around it by asking mockery to call the original constructor.

``` php
$customer = m::mock('\Stripe\Customer', []);
```

That should allow stripes `__set` code to work.

**Comment by salcode** [comment]
@davedevelopment 

Thanks for your notes, you're right your solution works but I am perplexed as why.  😕 

If I'm reading this correctly, it looks like we're passing in an empty expectation array `[]` but I am not clear on how that impacts the behavior of the code.

I realize you are busy and appreciate the time you've already spent on this.  If you could point me in the right direction (e.g. relevant documentation, the source code impacting this, or even a keyword I could Google), I'd really like to understand this more deeply.  If there isn't a quick URL or keyword that would be helpful, please feel free to skip it - I'm sure you're time is already spread thinly.

In any case thank you for all your work on Mockery, while I'm still rather new to using it I can see it is a great tool and appreciate how it has helped me already. 👍

**Comment by davedevelopment** [comment]
@salcode it's no problem at all. 

The `Mockery::mock` method is a bit of a beast :bear:

If you pass in an associative array, `['key' => 'value']`, Mockery takes those as a quick way to set up some stubs. 

If you pass an indexed array, `['value']`, Mockery takes those as constructor arguments and calls the original class's constructor with them.

Because the `StripeObject` class sets up a few things in it's constructor, forcing the constructor to be called allows the `StripeObject::__set` method to work nicely.

Passing constructor arguments is particularly useful for [partial mocks](http://docs.mockery.io/en/latest/reference/partial_mocks.html?highlight=constructor#traditional-partial-mock), where you want some of the mock object to behave as it would and use real code -

**Comment by salcode** [comment]
@davedevelopment thank you for this very clear and complete explanation, I get it now 😀 

I appreciate you not only providing a solution but helping me understand it.

I will certainly keep in mind these techniques as I use mockery in the future.

I'm going to mark this issue closed.  Thanks again.
